### ISSUE TITLE
NSGregorianCalendar Warnings

### ISSUE THREAD

**Issue by pickett** [apptentive/apptentive-ios#134]
This line (and others like it) throws a warning in apps compiled for iOS 8.
```
NSCalendar *calendar = [[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar];
```

Are there plans to update this?

**Comment by frankus** [comment]
These have been updated to the newest formats (e.g. NSGregorianCalendar -> NSCalendarGregorian, NS<time periond>CalendarUnit -> NSCalendarUnit<time period>).
