### ISSUE TITLE
convert to over-ride-able storyboards ?

### ISSUE THREAD

**Issue by orff** [apptentive/apptentive-ios#144]
At our company ( Viacom ), we distribute our internal components with CocoaPods.  For our brand tech teams to be able to customize the views, we have a "generic" storyboard with the view templates, and then the implementor of the library can override the storyboards by copying it to their local bundle and then customizing it.  Can you guys consider moving to a system like this where the library views are customizable in the same way that Apple suggests we do our views in our apps ( storyboards / auto layout / size classes ).

**Comment by frankus** [comment]
We are now using a single storyboard file for all UI in the Apptentive SDK, which the exception of alert views/alert controllers (which can't be set up in storyboards) and the survey UI (which will be updated in a forthcoming release).
