### ISSUE TITLE
UI iOS 9 beta

### ISSUE THREAD

**Issue by detouch** [apptentive/apptentive-ios#151]
Calling [[ATConnect sharedConnection] **presentMessageCenterFromViewController**:self]
for the first time
on iOS 9 (beta 3) on iPhone 6+
results in the **pop-up window being displayed off-screen** (too far up).

**Comment by Dids** [comment]
+1

**Comment by pkamb** [comment]
Hi, thanks for the issue. We will be releasing an update with initial fixes for iOS 9 in the near future. I'll post that here when it is ready.

**Comment by pickett** [comment]
Hey @pkamb any ETA on iOS 9, didn't see an active branch on github! Thanks in advance, Ben!

**Comment by pkamb** [comment]
Hi @detouch @Dids @pickett 

We've just released version 2.0.0, with iOS 9 support + many other changes.
https://github.com/apptentive/apptentive-ios/releases/tag/v2.0.0

Please give this version a try in your app, and let us know if you see any other issues with iOS 9. We have been testing on the latest beta and there are no known issues. Thanks!

**Comment by pickett** [comment]
Wow! Huge! Way to go. I'll check it out soon. 



————
Sent via Mobile
