### ISSUE TITLE
iOS 9 Betas: TLS v1.2 requirement issue (App Transport Security)

### ISSUE THREAD

**Issue by valheru7** [apptentive/apptentive-ios#152]
Hey guys

Experimenting with iOS 9 Beta, I had to update this for my app as well because my google app engine servers do not support TLS v1.2 yet either.

This is the issue: http://stackoverflow.com/questions/30720813/cfnetwork-sslhandshake-failed-ios-9

Essentially a ton of these in the logs: CFNetwork SSLHandshake failed (-9824) NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9824)

I assume that apptentive's servers are not up to TLS v1.2 yet.

The workaround is talked about in that answer as well as here: http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

For now, setting a 'globally ignore this TLS v1.2 requirement' in the info plist seems to fix it. (or adding exceptions for trusted domains)

**Comment by pkamb** [comment]
Hi, thanks for this! We will be issuing an update with a fix for this soon, and I'll update the ticket then.

**Comment by pkamb** [comment]
Hello, this issue should now be fixed (no SDK update required). Please let me know if you continue to see any issues related to TLS in iOS 9!
