### ISSUE TITLE
Frame squeeze on Ratings Alert

### ISSUE THREAD

**Issue by sharjeelnisar1** [apptentive/apptentive-ios#153]
On Displaying "Do you Love XYZ" alert, frame of my app is pushed down, half of the screen and around 20 pixels from the left.

Above portion becomes black and all of the UI behaves like that. On killing app and restarting brings its UI to normal Position. Please fix this issue ASAP. We'r facing download decrease due to this issue.

**Comment by pkamb** [comment]
Hello, can you please add a picture of this issue in your app? Thanks!

**Comment by pkamb** [comment]
Hello, the "Do you Love" alert has been switched to use `UIAlertController` in version 2.0.0. Please give that a try, and let me know if you are still having this issue.

https://github.com/apptentive/apptentive-ios/releases/tag/v2.0.0
