### ISSUE TITLE
CocoaPods Linker Error

### ISSUE THREAD

**Issue by msuprovici** [apptentive/apptentive-ios#154]
When I enter my apiKey I get the following errors:

```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_ATConnect", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When I comment it out but leave the "ATConnect.h" import, the project builds.  Any advice here?

**Comment by pkamb** [comment]
Hi, there are a couple common causes for this error.

I would guess it's from forgetting to link ApptentiveConnect in the `Link Binary With Libraries` build phase?

Let me know if that helps, and we can debug further.

Some other solutions here:
http://stackoverflow.com/questions/6429494/undefined-symbols-for-architecture-armv7

**Comment by msuprovici** [comment]
Sorry, I forgot to mention that I'm using cocopods.  Does this still apply?

**Comment by pkamb** [comment]
Do either of these answers help?

http://stackoverflow.com/questions/27286226/undefined-symbols-for-architecture-armv7-for-cocoapods-libraries

http://stackoverflow.com/questions/18132995/cocoapods-flurry-testflight-undefined-symbols-for-architecture

**Comment by msuprovici** [comment]
Nope.  Tried all the above. But no go.

**Comment by pkamb** [comment]
Ah, here is my answer for the same issue (with Apptentive) in the past. Hoping that this fixes it for you, but let me know!

http://stackoverflow.com/questions/20864172/undefined-symbols-error-when-integrating-apptentive-ios-sdk-via-cocoapods

Check your linker flags:


    Target > Build Settings > Other Linker Flags

You should see `-lApptentiveConnect` listed as a linker flag:

    ... -ObjC -lApptentiveConnect ...

**Comment by msuprovici** [comment]
Yup, I saw this before I reached out.  I don't see -lApptentiveConnect  but I do see "apptentive-ios".  When I try to manually add it to my linker flags I get this:

ld: library not found for -lApptentiveConnect
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pkamb** [comment]
You're opening the Xcode workspace, and not the project file, right?

Is CocoaPods properly installed / updated for your pods?

http://stackoverflow.com/questions/23539147/xcode-ld-library-not-found-for-lpods

**Comment by msuprovici** [comment]
Yes & yes.  I just verified that I'm up to date - cocoapods-0.38.2  Also
just re-installed everything to make sure, but I get the same errors.

**Comment by msuprovici** [comment]
Seems like this is a cocoapods issue and not and with Apptentive.

**Comment by mmvlad** [comment]
Did you fix it?

**Comment by frankus** [comment]
@mmvlad Are you seeing a problem along these lines with the Apptentive SDK?

**Comment by mmvlad** [comment]
I was getting this error when building my Unity project for iOS simulator. May be that was a reason. Didn't get a chance to test the same project on real device for now.
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_ATConnect", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by frankus** [comment]
Unity isn't something we currently officially support, so we haven't tested integrating via CocoaPods in a Unity project. 

Have you used other pods successfully? If not, I would suggest trying a source-level integration, as described here: http://www.apptentive.com/docs/ios/setup/xcode/.

**Comment by frankus** [comment]
You may also find this useful: https://groups.google.com/d/msg/cocoapods/6S0qbXKAbaw/q8jTWNA34mgJ

**Comment by Leomax004** [comment]
Anyone facing such kind of Error:
Unable to load class named 'ATEvent' for entity 'ATEvent

**Comment by frankus** [comment]
Which SDK version is this? Does it still occur on the latest (3.2.1)?

**Comment by Leomax004** [comment]
yeah it's latest but now i solved by cleaning the code.
