### ISSUE TITLE
Missing storyboard 'MessageCenter' (2.0.0)

### ISSUE THREAD

**Issue by Natelegreat1** [apptentive/apptentive-ios#155]
As soon as I loaded the new version via cocoa pods (2.0.0), I started getting these crashes upon trying to 'presentMessageCenterFromViewController'  : 

    'Could not find a storyboard named 'MessageCenter' in bundle NSBundle </var/mobile/Containers/Bundle/Application/004838EE-512F-4F60-AB71-82E3D788AF96/StudyBuddy.app/ApptentiveResources.bundle> (not yet loaded)'

**Comment by pickett** [comment]
Same here

**Comment by pickett** [comment]
Here's a stacktrace:

```
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001089e59b5 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000108166deb objc_exception_throw + 48
	2   UIKit                               0x000000010611c4f7 -[UIStoryboard name] + 0
	3   FreeTime                            0x000000010450cb24 -[ATInteractionMessageCenterController showMessageCenterFromViewController:] + 292
	4   FreeTime                            0x00000001044fc179 -[ATEngagementBackend presentMessageCenterInteraction:fromViewController:] + 585
	5   FreeTime                            0x00000001044fb4b4 -[ATEngagementBackend presentInteraction:fromViewController:] + 852
	6   FreeTime                            0x00000001044f947e -[ATEngagementBackend engageCodePoint:fromInteraction:userInfo:customData:extendedData:fromViewController:] + 846
	7   FreeTime                            0x0000000104505f89 -[ATInteraction engage:fromViewController:userInfo:customData:extendedData:] + 313
	8   FreeTime                            0x0000000104505dff -[ATInteraction engage:fromViewController:userInfo:] + 143
	9   FreeTime                            0x0000000104505d34 -[ATInteraction engage:fromViewController:] + 100
	10  FreeTime                            0x00000001044df162 -[ATBackend presentMessageCenterFromViewController:withCustomData:] + 706
	11  FreeTime                            0x00000001044dee70 -[ATBackend presentMessageCenterFromViewController:] + 64
	12  FreeTime                            0x00000001044e8a7c -[ATConnect presentMessageCenterFromViewController:] + 92
	13  FreeTime                            0x00000001044085ce -[FTSettingsViewController tableView:didSelectRowAtIndexPath:] + 2766
	14  UIKit                               0x0000000105b97775 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1948
	15  UIKit                               0x0000000105b97990 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 330
	16  UIKit                               0x0000000105a6d7e6 _runAfterCACommitDeferredBlocks + 317
	17  UIKit                               0x0000000105a7f348 _cleanUpAfterCAFlushAndRunDeferredBlocks + 95
	18  UIKit                               0x0000000105a8ae5c _afterCACommitHandler + 90
	19  CoreFoundation                      0x0000000108911457 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	20  CoreFoundation                      0x00000001089113c7 __CFRunLoopDoObservers + 391
	21  CoreFoundation                      0x000000010890701b __CFRunLoopRun + 1147
	22  CoreFoundation                      0x0000000108906918 CFRunLoopRunSpecific + 488
	23  GraphicsServices                    0x000000010b795ad2 GSEventRunModal + 161
	24  UIKit                               0x0000000105a6199e UIApplicationMain + 171
	25  FreeTime                            0x0000000104420a9f main + 111
	26  libdyld.dylib                       0x0000000108ed292d start + 1
	27  ???                                 0x0000000000000001 0x
```

**Comment by pickett** [comment]
@Natelegreat1 if you download a zip of the Apptentive SDK and pull in Main Storyboard and Message Center Storyboards it will work but I'm not sure @pkamb if there need to be storyboards for each localization (as it appears in your localizaiton files). 

Either way, seems to just be a pods dependency issue.

**Comment by Natelegreat1** [comment]
@pickett I figured it was just some pods dependency issue. I just ended up switching to Helpswift instead just out of shear frustration. Maybe I'll give them another chance once I see the what this 2.0 looks like. Nice catch with running it manually!

**Comment by Natelegreat1** [comment]
Whoops. Didn't mean to close. Still a valid Issue!

**Comment by pkamb** [comment]
Thanks for bringing this up, and sorry for the issue here with CocoaPods. Looking into this...

**Comment by pkamb** [comment]
Sorry for the issue here. The commit above should fix the crash you are seeing, by adding our Storyboard to the CocoaPods resources bundle. 

After pulling that commit, this fix can be added as a local CocoaPod in your Podfile like so:  

    pod 'apptentive-ios', :local => "~/path/to/local/apptentive-ios"

The resulting build is now however missing the images in our UI, which as of 2.0.0 have been added to an Asset Catalog. The Resources Bundle of our non-cocoapods builds (CC 7e42145ac7161f4063538e2c4f13dd7b9b2b7538) still include individual images in addition to the `.xcassets`/`.car` asset catalogs, these individual images still being needed for iOS 7. 

The CocoaPods build is currently not including these individual images in the bundle. Same issue as this:
http://stackoverflow.com/questions/21857986/how-can-i-load-an-image-from-assets-car-compiled-version-of-xcassets-within-an

We'll be looking into the missing images next, but the commit above will at least fix the crash for the missing Storyboard.

**Comment by pickett** [comment]
@pkamb thanks for jumping on this

**Comment by danielzev** [comment]
+1

**Comment by jeremyprovost** [comment]
+1

**Comment by pkamb** [comment]
Hi folks, we have a fix for the Storyboard and the missing images on the cocoapods branch here: https://github.com/apptentive/apptentive-ios/tree/cocoapods

Will be releasing a 2.0.1 release for cocoapods now, I'll post again when that is available.

**Comment by danielzev** [comment]
Good work guys :+1:

**Comment by pkamb** [comment]
2.0.1 should now be available from CocoaPods: 
https://cocoapods.org/?q=apptentive-ios

and also on our Releases page:
https://github.com/apptentive/apptentive-ios/releases/tag/v2.0.1

Please let me know if you experience any other issues with CocoaPods or with the 2.0 release in general! Thanks for using Apptentive.
