### ISSUE TITLE
Apptentive Rating Prompt not shown for Event - version 2.0

### ISSUE THREAD

**Issue by huynhduyson** [apptentive/apptentive-ios#158]
My source code:

AppDelegate.m
```
application:didFinishLaunchingWithOptions:
[ATConnect sharedConnection].apiKey = APPTENTIVE_API_KEY;
[ATConnect sharedConnection].appID = appStoreID;
```

MyViewController.m
```
viewDidLoad:
 [[ATConnect sharedConnection] engage:kEventViewCity fromViewController:self];
```

Rating Prompt configuration:
<img width="833" alt="screen shot 2015-09-24 at 11 49 34 pm" src="https://cloud.githubusercontent.com/assets/8979691/10080679/41b6b20e-631b-11e5-9b9c-289ceb7b3001.png">
<img width="834" alt="screen shot 2015-09-24 at 11 49 52 pm" src="https://cloud.githubusercontent.com/assets/8979691/10080681/443a7d58-631b-11e5-82a2-aa20fdbba0fc.png">
<img width="837" alt="screen shot 2015-09-25 at 12 04 40 am" src="https://cloud.githubusercontent.com/assets/8979691/10080685/45df3658-631b-11e5-94e8-fcad9ea6221b.png">

**Comment by frankus** [comment]
Thanks for the detailed report. 

To quickly get to the bottom of this, set a breakpoint on line 113 of ATInteractionInvocation.m, trigger your event, and when it hits the breakpoint, print a description of both the `predicate` and the `[usageData predicateEvaluationDictionary]` variables. You can then mentally substitute the values from the latter into the expression in the former and figure out what criteria aren't being met. 

While I can't rule out a problem on our end, here are some things that might be causing the issue:

- Make sure you're actually closing the app (using a real or simulated home button press) and leaving it inactive for 30 seconds or so (we have a floor on what sort of inactive time constitutes a "launch") before relaunching (tapping the app icon). 
- Set your device/Mac clock ahead one day to make sure you're not hitting the "Wait for n days after the first launch of the current app version" limit. 
- Make sure the prompt hasn't been shown before for that app version (i.e. delete the app before running it again).

**Comment by huynhduyson** [comment]
Thanks for the quickly response from you.

**Comment by huynhduyson** [comment]
It's working perfectly. Thanks for your support @frankus
