### ISSUE TITLE
The Traditional Chinese Localization folder for iOS is incorrecct

### ISSUE THREAD

**Issue by naikling** [apptentive/apptentive-ios#159]
Switch your iOS language to Traditional Chinese and start Message Center inside an app will see English "Message Center" instead of the localized version. 

The problem is the localized folder name for traditional Chinese is not zh.lproj  it should be zh-Hant.lproj
by changing the folder name to zh-Hant.lproj you should see the proper localized version.

Change 
apptentive-ios/ApptentiveConnect/resources/localization/ zh.lproj 
to
apptentive-ios/ApptentiveConnect/resources/localization/ zh-Hant.lproj

Thanks

**Comment by frankus** [comment]
Thank you for your help with this. It will be fixed in an upcoming release.

**Comment by frankus** [comment]
This should be fixed in version 2.0.4.
