### ISSUE TITLE
https warning when opening message center

### ISSUE THREAD

**Issue by mackuba** [apptentive/apptentive-ios#166]
Hi,

I'm getting warnings like this when I open the message center:

> 2016-01-14 16:59:20.129 Zoomer[57405:5071896] [error] Unable to download image at http://a4.mzstatic.com/us/r30/Purple3/v4/ca/54/68/ca54682f-14f5-70bd-56a5-aa06b108ac39/icon175x175.jpeg: Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSUnderlyingError=0x7fb8e8ea49a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSErrorFailingURLStringKey=http://a4.mzstatic.com/us/r30/Purple3/v4/ca/54/68/ca54682f-14f5-70bd-56a5-aa06b108ac39/icon175x175.jpeg, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLKey=http://a4.mzstatic.com/us/r30/Purple3/v4/ca/54/68/ca54682f-14f5-70bd-56a5-aa06b108ac39/icon175x175.jpeg}}, NSErrorFailingURLStringKey=http://a4.mzstatic.com/us/r30/Purple3/v4/ca/54/68/ca54682f-14f5-70bd-56a5-aa06b108ac39/icon175x175.jpeg, NSErrorFailingURLKey=http://a4.mzstatic.com/us/r30/Purple3/v4/ca/54/68/ca54682f-14f5-70bd-56a5-aa06b108ac39/icon175x175.jpeg, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.}

Looks like this is the app icon taken from the App Store page - any chance that can be loaded through https?

**Comment by frankus** [comment]
I will check with our platform team to see if this is a change we can make on the server. An workaround would be to upload your app icon image to the Apptentive dashboard, which will load it over https.

**Comment by frankus** [comment]
I think we have this solved server-side, by rehosting the images in question behind compliant SSL.
