### ISSUE TITLE
Add shared framework scheme / Carthage support

### ISSUE THREAD

**Issue by joshbax** [apptentive/apptentive-ios#167]
Request for adding a target to build as a dynamic framework so we can easily integrate apptentive into swift projects

**Comment by frankus** [comment]
Thanks for the request :)

We will definitely do this by the time we drop iOS 7 support (sometime in Q3 of this year), and we'll consider providing an option for this sooner if we can.

**Comment by frankus** [comment]
If CocoaPods is an option for you, we now set a module name that removes the need for a bridging header. Instead you just `import Apptentive` at the top level of any files where you need it.

**Comment by joshbax** [comment]
Thanks, 
I am still using Cocoapods with the frameworks option, but hoping to eventually migrate away from it. It's not a huge priority; I put in in the request so it can be tracked.
I haven't tried, but it's probably straight forward enough to fork and create a shared framework targeting iOS8? Maybe I'll do that if I get really anxious.

**Comment by frankus** [comment]
I just pushed an experimental branch that does this ("framework"). It's not something we can support just yet, but feel free to take a look and, as always, PRs are welcome.

**Comment by joshbax** [comment]
:+1: 

Thanks for the quick turn around. I'll try it out next week.

**Comment by joshbax** [comment]
Loaded up the framework branch without a problem, haven't tested everything but so far it's working as normal.

**Comment by mAu888** [comment]
Carthage support is working for us. Except that pinning to a branch sometimes leads to endless fetching the Apptentive framework when running `carthage update`. There are already some issues filed showing similar behaviour in Carthage (see Carthage/Carthage#733 for example). So any chance this is being integrated soon?

**Comment by joshbax** [comment]
@mAu888 I haven't tried this yet, but I believe you can do `carthage archive` on your apptentive fork and and then attach the archive to a custom apptentive "release". Make sure to point carthage to your custom release, and then carthage should use that binary instead of going through a fetch/build cycle each time you update.

**Comment by mAu888** [comment]
Ended up forking and putting a custom version on it. Anyways, any chance this feature will make it at some point @frankus?

**Comment by frankus** [comment]
The v3.3.1 branch (currently a prerelease) adds a framework scheme for Carthage. 

Feedback is greatly appreciated!

**Comment by frankus** [comment]
This is now in the official release of 3.3.2. Please let me know if you find any issues with it.
