### ISSUE TITLE
[Simulator] Apptentive 2.1 Crash "NSManagedObjectContext error" in "ATDataManager setupAndVerify"

### ISSUE THREAD

**Issue by Sudopanda** [apptentive/apptentive-ios#168]
<img width="383" alt="screen shot 2016-02-03 at 3 44 04 pm" src="https://cloud.githubusercontent.com/assets/17055551/12800866/08dcf6da-ca8d-11e5-9ea4-2eccfa6ab6dd.png">

Using the latest release from https://github.com/apptentive/apptentive-ios/releases
apptentive_ios_sdk-2.1.1.tar.gz

After upgrading from 2.0.5 we encounter this crash on startup every time only in the simulator. We are forced to downgrade so we can continue development. This crash does not occur when built onto the device.

**Comment by frankus** [comment]
Is this an upgrade scenario or a clean install? (obviously it should work both ways, but that will help me narrow it down). 

If it's an upgrade, would you be able to send me the contents of the com.apptentive.feedback directory (in your app's Application Support directory)?

**Comment by Sudopanda** [comment]
Simple upgrade where I replaced the 3 files ATConnect.h, libApptentiveConnect.a and ApptentiveResources.bundle from the zip one for one. I also tried a clean install with the same result. 

Contents of com.apptentive.feedback
ATDataManagerUpgradeCanary
ATDataModel.sqlite
[com.apptentive.feedback.zip](https://github.com/apptentive/apptentive-ios/files/117966/com.apptentive.feedback.zip)

**Comment by frankus** [comment]
Is there a particular iOS version this is happening on? Device or Simulator (or both)? Thanks for your help so far in tracking this down :)

**Comment by Sudopanda** [comment]
Simulator Online
Tested 9.2 and 8.4

**Comment by frankus** [comment]
I'm able to reproduce this symptom by using an older version of ApptentiveResources.bundle with the newest libApptentiveConnect.a file. Is there any chance that a stale version of the bundle is ending up on your simulator?

**Comment by Sudopanda** [comment]
So I had already tried a clean build and also tried resetting contents on the device none of that work.
After your comment I decided to go in an not only clear all the derived data but manually delete any other previous instances and builds. 

This appears to have finally done the trick. Thank you for your comment :)

**Comment by frankus** [comment]
Happy to help!
