### ISSUE TITLE
Embedded file paths in appetitive lib.

### ISSUE THREAD

**Issue by Sudopanda** [apptentive/apptentive-ios#170]
Hi
We recently made some changes to our build configurations from DWARF to dSYM which generated some warnings which we believe stem from third party libraries.

Example of warning
warning: /var/folders/dr/l7mlbx6s1wb061grlnkgpykr0000gn/C/org.llvm.clang.frank/ModuleCache/2H28LYPN5S6B1/UIKit-1V5UHAPTOD24G.pcm: No such file or directory

After digging around online I believe this is because the /var/folders/dr/… path is embedded in the library. 
Suggestions online are to rebuild 3rd party libs (in this case libApptentiveConnect.a) with Precompile Prefix (GCC_PRECOMPILE_PREFIX_HEADER) = NO and if that still causes issues to try Precompile Prefix (GCC_PRECOMPILE_PREFIX_HEADER) = NO

Are you able to confirm our findings and if so can this be fixed? Running apptentive 2.1.1

Thanks

**Comment by frankus** [comment]
We set CLANG modules to be disabled in the Apptentive SDK in version 2.1.3 in an effort to remove these warnings. This should not affect the integration process at all.

If you have a minute, try updating to 2.1.3 and let us know if our fix worked. Thanks!

**Comment by Sudopanda** [comment]
Still same issue in 2.1.3

libApptentiveConnect.a(ATPassThroughWindow.o):
warning: /var/folders/dr/l7mlbx6s1wb061grlnkgpykr0000gn/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/ApptentiveConnect-Prefix-adhcrrsmujlxhdghyrotjjqledut/ApptentiveConnect-Prefix.pch.pch: No such file or directory

**Comment by frankus** [comment]
Have you been able to try this with the latest SDK release (https://github.com/apptentive/apptentive-ios/releases/tag/v3.1.1)? We made some changes to support bitcode that seem to have also fixed the warnings when integrating via static library. 

I've tested this on a separate user account, but haven't had a chance to try it on a different machine.

**Comment by Sudopanda** [comment]
Yes we have updated to the latest SDK 3.2 and it has cleared all our error and warnings.

Thanks
