### ISSUE TITLE
Mechanic for forcing a rating prompt to show.

### ISSUE THREAD

**Issue by android1989** [apptentive/apptentive-ios#171]
We currently have a button in our settings which we want to force the rating prompt, but their isn't an explicit call to do so. 

Is there a proper workaround for this issue?

**Comment by frankus** [comment]
We don't have public API to show the ratings prompt, but you could use the `-openAppStore` method directly (which opens the app store to the review page of your app) and use a title for your button that indicates that the user will be taken straight to the app store to rate your app.
