### ISSUE TITLE
Apptentive build broken in Cocoapods 1.0.0-beta6

### ISSUE THREAD

**Issue by jlyonsmith** [apptentive/apptentive-ios#172]
Not sure if this is an Apptentive SDK issue or a Cocoapods issue but wanted to give you heads up so you can investigate.  Tried upgrading to Cocoapods 1.0.0-beta6 today and everything worked fine except for the trying to copy the ApptentiveResources.bundle.  I got an error saying that the bundle could not be found.  I noticed in the `apptentive-ios-ApptentiveResources` target that the _Per-configuration Build Products Path_ ended with `.../Build/Products/Debug-iphonesimulator/apptentive-ios/apptentive-ios`.  Note the two `apptentive-ios` dirs.  There should just be one.

**Comment by hamdan** [comment]
Same issue any solution?

**Comment by frankus** [comment]
We'll be including a fix in our next release.

**Comment by frankus** [comment]
Update: CocoaPods 1.0.0 beta 8 includes a fix for this issue. Please update CocoaPods and give it another try.
