### ISSUE TITLE
Sending message fails with "Bad Request"

### ISSUE THREAD

**Issue by tigerline** [apptentive/apptentive-ios#173]
Xcode 7.3
Simulator iPhone 6 / iOS 9.3
Apptentive iOS SDK 3.0, API Key of a freshly created dummy app

Steps:
- Install and run app in simulator for first time
- Open message center with `presentMessageCenterFromViewController:`
- Type "hello" in message field
- Press Send
- Sending message fails 👎 

Console output:
> [error] Connection failed. Bad Request, bad request
> [info] Status was: 400
> [error] Invalid JSON: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
> [error] Error decoding error response: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
2016-05-06 09:52:33.074 Tigerline[6907:979793] [info] ApptentiveAPIRequest failed: Invalid response from server., Server did not return properly formatted JSON.

**Comment by frankus** [comment]
Is this still occurring? We changed our JSON decoding on the server in a way that made some invalid assumptions (which should now be corrected).

**Comment by frankus** [comment]
Closing for now. Please reopen if you see this again.
