### ISSUE TITLE
Bitcode not enabled for sdk-2.1.3, is this issue fixed in 3.0.0?

### ISSUE THREAD

**Issue by Dipakvyawahare** [apptentive/apptentive-ios#176]
Hello,

Which version is bit code enabled? 
libApptentiveConnect.a(ATPassThroughWindow.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

Thanks

**Comment by Dipakvyawahare** [comment]
Thanks

**Comment by CestLou** [comment]
👍
