### ISSUE TITLE
Breaking Constraints

### ISSUE THREAD

**Issue by aquigriffin** [apptentive/apptentive-ios#178]
Debug Console is giving the following warning when displaying MessageCenter:

**Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    \<NSAutoresizingMaskLayoutConstraint:0x15eee1890 h=--& v=--& V:[UIView:0x15ed4cf40(0)]\>,
    \<NSLayoutConstraint:0x15ee170b0 V:|-(8)-[UIView:0x15ecf6160]   (Names: '|':ApptentiveMessageCenterInputView:0x15e85a630 )\>,
    \<NSLayoutConstraint:0x15e9988e0 V:[UIView:0x15ecf6160]-(8)-|   (Names: '|':ApptentiveMessageCenterInputView:0x15e85a630 )\>,
    \<NSLayoutConstraint:0x15ed14a00 V:|-(0)-[ApptentiveMessageCenterInputView:0x15e85a630]   (Names: '|':UIView:0x15ed4cf40 )\>,
    \<NSLayoutConstraint:0x15d7ca260 V:[ApptentiveMessageCenterInputView:0x15e85a630]-(0)-|   (Names: '|':UIView:0x15ed4cf40 )\>
)

Will attempt to recover by breaking constraint 
\<NSLayoutConstraint:0x15e9988e0 V:[UIView:0x15ecf6160]-(8)-|   (Names: '|':ApptentiveMessageCenterInputView:0x15e85a630 )\>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.**

This is occurring as of 3.0.0.

**Comment by frankus** [comment]
Please try it with 3.1.0. Among the other changes we included a fix for that problem. Thanks!

**Comment by aquigriffin** [comment]
Thanks.
