### ISSUE TITLE
iOS 10 Warnings - awakeFromNib

### ISSUE THREAD

**Issue by aquigriffin** [apptentive/apptentive-ios#180]
Ensure [super awakeFromNib] is being called for iOS10.
https://udid.co/iOS_10_beta_Release_Notes.pdf

**Comment by frankus** [comment]
Thanks for the report!

We have a fix for this ready for our next release. I'll circle back when that happens.

**Comment by aquigriffin** [comment]
Thanks @frankus for the quick response.

**Comment by frankus** [comment]
This should be fixed in 3.2.
