### ISSUE TITLE
APIKey renamed to apiKey in Swift 3

### ISSUE THREAD

**Issue by plarson** [apptentive/apptentive-ios#181]
Is there no way to set the APIKey value when using Swift 3?

**Comment by frankus** [comment]
We'll have a release out in the next couple of days that addresses this. 

In the meantime you can edit Apptentive.h and add the NS_SWIFT_UNAVAILABLE to the lowercase `apiKey` property.

**Comment by frankus** [comment]
This should be fixed in the 3.3.0 release. Please reopen if you run into problems. Thanks!
