### ISSUE TITLE
OneBusAway crashing upon setting API key w/ SDK 3.3.0

### ISSUE THREAD

**Issue by aaronbrethorst** [apptentive/apptentive-ios#182]
Branch is here: https://github.com/aaronbrethorst/onebusaway-iphone/tree/fix-725

Hopefully I just missed something silly :) 

fwiw, I saw this in the last version, too.

**Comment by frankus** [comment]
It's not picking up a (any?) category from the Apptentive project. You can fix it by adding -ObjC to the Other Linker Flags build setting.

**Comment by aaronbrethorst** [comment]
party like it's 2010, thanks :)
