### ISSUE TITLE
Error: couldn't read cache file to update store info timestamps

### ISSUE THREAD

**Issue by Taarna** [apptentive/apptentive-ios#184]
Hello,

We started receiving this error message ever since we updated to Xcode 8. We're using Swift 2.3 and Apptentive SDK 3.3.0.

I searched Apptentive project and found a cache named @"at-unread-messages-cache" in ApptentiveBackend.m and ApptentiveMessageCenterDataSource.m. 
Our app uses CoreData, but none of our NSFetchResultsControllers are using cache. Other libraries in the app are not using CoreData at all. Also, the message doesn't appear if I disable Apptentive.

It happens on phones and simulators. I tried iPhone 5, iPhone 5s, iPhone 6 and iPhone 7. The error message appeared for all of them, but only on iOS 9 and iOS 10 (never on iOS 8).

This is the log:

[info] Apptentive SDK Version 3.3.0
[debug] Setting up data manager
[debug] Creating conversation
[debug] Apptentive Reachability changed: WiFi
[info] Engage Apptentive event: com.apptentive#app#launch
[info] Conversation created successfully.
[info] Received remote Interactions from Apptentive.
[error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
[error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
[error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
[error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
[error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
[error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
[error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
[error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps

This is how it looks like on iOS 8:

[info] Apptentive SDK Version 3.3.0
[debug] Setting up data manager
[debug] Creating conversation
[debug] Apptentive Reachability changed: WiFi
[info] Engage Apptentive event: com.apptentive#app#launch
[info] Conversation created successfully.
[info] Received remote Interactions from Apptentive.

**Comment by frankus** [comment]
Thanks for the detailed report. 

We will be removing the cache file specifier for the unread count fetched results controller. For Message Center's section info cache, we'll be removing it for iOS 9 and 10, which seem to have a bug related to the file.

**Comment by azeemse** [comment]
Hello @frankus 

I just downloaded the SDK and integrated in my game. I need to show the **Ratings Prompt**. My project is developed in Swift and I am using Xcode 8 with iOS 10 for my device iPhone 6s Plus.

I am still getting the above mentioned issue. The log is as same as @Taarna  has mentioned in his report.

When I call

`[[Apptentive sharedConnection] engage:@"completed_level" fromViewController:viewController];`

following log is printed in console

```
Engage Apptentive event: local#app#Level_complete
2016-10-24 12:24:25.037884 Canon Hero[1243:468196] [error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
2016-10-24 12:24:25.038205 Canon Hero[1243:468196] [error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
2016-10-24 12:24:25.054900 Canon Hero[1243:468221] [info] Interaction 57f2c7beb129482b4300002d predicate failed evaluation.
2016-10-24 12:24:25.060068 Canon Hero[1243:468220] [info] Interaction 57f2c7beb129482b4300002b predicate failed evaluation.
2016-10-24 12:24:25.088407 Canon Hero[1243:468221] [info] Received remote Interactions from Apptentive.
2016-10-24 12:24:29.944143 Canon Hero[1243:468196] [error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
2016-10-24 12:24:29.944928 Canon Hero[1243:468196] [error] error:  (NSFetchedResultsController): couldn't read cache file to update store info timestamps
```


Please let me know the solution.

Warm Regards

**Comment by brianminor** [comment]
Any info on when this will be removed it's quite annoying with my logs?

**Comment by frankus** [comment]
The latest release (3.3.2) includes a fix for this.
