### ISSUE TITLE
NSPhotoLibraryUsageDescription required in iOS10?

### ISSUE THREAD

**Issue by bejar37** [apptentive/apptentive-ios#186]
Hi, I'm using version 3.0.0 of your SDK, and submitting for the first time using Xcode 8. I got an invalid binary email from Apple stating:

`This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.`

It seems like apptentive is referencing `UIImagePickerView` which is triggering this static analysis rejection from Apple. Is this a feature of your API that can be turned off?

**Comment by frankus** [comment]
While you can choose whether or not to use Message Center (including its image attachment feature), we currently don't have a straightforward way of excluding that capability from your app's binary. 

We suggest including a string such as "This allows attaching images to messages." for the usage description. It will only be shown to users if and when they tap the attach (paperclip) button in message center. 

Finally, although we don't recommend it, you could fork the SDK and remove the image attachment feature.

**Comment by bejar37** [comment]
OK, thanks!
