### ISSUE TITLE
App doesn't receive notification: ApptentiveMessageCenterUnreadCountChangedNotification

### ISSUE THREAD

**Issue by Rommanski** [apptentive/apptentive-ios#187]
Hello, I have registered for notification with:

```
NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(unreadMessageCountChanged), name: ApptentiveMessageCenterUnreadCountChangedNotification, object: nil)
```

And method:

```
func unreadMessageCountChanged(notification : NSNotification) {
        let count = notification.userInfo?["count"]
        print("unreadMessageCountChanged: \(count)")
    }
```

App receives notification when user opens app or user opens messenger center only. Otherwise notification doesn't arrive. Don't have any idea.

**Comment by frankus** [comment]
When the user is not in Message Center, the interval at which the SDK checks for new messages is five minutes (the SDK polls more frequently when Message Center is in the foreground), and we don't do any polling at all when your app is in the background. 

The best way to eliminate that latency is to enable push notifications, as described [here](https://learn.apptentive.com/knowledge-base/apptentive-ios-sdk/#push-notifications).

**Comment by Rommanski** [comment]
Thank you @frankus for help!
