### ISSUE TITLE
using static lib does not work [don't use "use_frameworks" flag in cocoapod]

### ISSUE THREAD

**Issue by radelcom** [apptentive/apptentive-ios#191]
I was investigating of integrating Apptentive to our application. Our project uses Cocoapods for 3rd party libraries and do not use `use_frameworks` flag.  Looks like Apptentive doesn't work with this and give error that the static library is not found.

Judging from the error and looking at the Pods, it seems like `libapptentive-ios.a` fails to compile.
![screen shot 2017-03-28 at 9 55 45 am](https://cloud.githubusercontent.com/assets/1000753/24417337/e0c00494-139c-11e7-8c64-4d82ab30e7b9.png)

**Comment by frankus** [comment]
You'll need to use a workaround if you aren't able to use the `use_frameworks!` directive, in the form of a post-install hook in your podfile:

```
post_install do |pi|
    pi.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            unless pi.podfile.defined_in_file.read().include? "\nuse_frameworks!\n"
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NO_USE_FRAMEWORKS=1'
            end
        end
    end
end
```

**Comment by radelcom** [comment]
@frankus tx, the workaround seems to work. Is there a plan to address this in the future so we dont need to have this workaround?

**Comment by frankus** [comment]
The need for the workaround was a result of adding both static library and framework targets to the project. In the next major version we will remove support for the standalone static library target (although CocoaPods will still be able to build a static library) which should fix this.
