### ISSUE TITLE
Cannot able to change back button in ApptentiveSurveyViewController

### ISSUE THREAD

**Issue by Ramanamurty** [apptentive/apptentive-ios#192]
Hi, I can able to access ApptentiveSurveyViewController in my application in older version of apptentive and change the back button image. But with latest version I cannnot able to access ApptentiveSurveyViewController in my app. Can someone please tell me how can I change the back button image in latest version

**Comment by frankus** [comment]
We don't expose the ApptentiveSurveyViewController header file publicly, but you might be able to add it to your header search paths. This would depend on your method of integration (CocoaPods/Carthage/Subproject). 

I should also mention that the navigation controller subclass used for Apptentive's UI (ApptentiveNavigationController) is exposed in the public headers. For UIAppearance targeting, this can be a good option.
