### ISSUE TITLE
App hangs when coming to foreground

### ISSUE THREAD

**Issue by matheda** [apptentive/apptentive-ios#194]
I updated our app to the version 4.0.1 SDK today and it now hangs when coming back to the foreground.  If I pause execution it is stuck in this method...

`- (BOOL)engageCodePoint:(NSString *)codePoint fromInteraction:(ApptentiveInteraction *)fromInteraction userInfo:(NSDictionary *)userInfo customData:(NSDictionary *)customData extendedData:(NSArray *)extendedData fromViewController:(UIViewController *)viewController`

... on this line of code, which is being called on the UI thread:

`	@synchronized(conversation) {`

It looks like this change was added on June 26th, 2017.

**Comment by frankus** [comment]
Thanks for reporting this. 

The 4.0 version introduced some major architectural changes to the SDK. We haven't seen this specific issue in testing, so I was hoping I could get a bit more information from you. 

From looking at the code and your report it seems like we might have a deadlock on the conversation object. Can you verify if removing the @synchronized block resolves the issue?

**Comment by wooster** [comment]
@matheda Also… when you do get the hang, could you run `thread backtrace all
` in lldb and send the output to frank@apptentive.com and andrew@apptentive.com? It would be good to know which two threads are trying to take a lock on the conversation.

**Comment by matheda** [comment]
Thank you for following up so quickly!

I removed the @sychronized wrapper around the two calls to the conversation object and that fixed the deadlock.

Here is the backtrace when the deadlock occurs:

* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x000000018a460e64 libsystem_kernel.dylib`__psynch_mutexwait + 8
    frame #1: 0x000000018a52cb8c libsystem_pthread.dylib`_pthread_mutex_lock_wait + 96
    frame #2: 0x000000018a52cd94 libsystem_pthread.dylib`_pthread_mutex_lock_slow + 300
    frame #3: 0x0000000189ed46f8 libobjc.A.dylib`recursive_mutex_tt<false>::lock() + 16
    frame #4: 0x0000000189ed7f28 libobjc.A.dylib`objc_sync_enter + 28
  * frame #5: 0x0000000101ffc47c Apptentive`-[ApptentiveBackend(self=0x0000000170136260, _cmd="engageCodePoint:fromInteraction:userInfo:customData:extendedData:fromViewController:", codePoint=@"com.apptentive#app#launch", fromInteraction=0x0000000173e6d340, userInfo=0x0000000000000000, customData=0x0000000000000000, extendedData=0x0000000000000000, viewController=0x0000000000000000) engageCodePoint:fromInteraction:userInfo:customData:extendedData:fromViewController:] at ApptentiveBackend+Engagement.m:108
    frame #6: 0x0000000102028e10 Apptentive`-[ApptentiveInteraction engage:fromViewController:userInfo:customData:extendedData:](self=0x0000000173e6d340, _cmd="engage:fromViewController:userInfo:customData:extendedData:", event=@"launch", viewController=0x0000000000000000, userInfo=0x0000000000000000, customData=0x0000000000000000, extendedData=0x0000000000000000) at ApptentiveInteraction.m:114
    frame #7: 0x0000000102028c68 Apptentive`-[ApptentiveInteraction engage:fromViewController:userInfo:](self=0x0000000173e6d340, _cmd="engage:fromViewController:userInfo:", event=@"launch", viewController=0x0000000000000000, userInfo=0x0000000000000000) at ApptentiveInteraction.m:108
    frame #8: 0x0000000102028b88 Apptentive`-[ApptentiveInteraction engage:fromViewController:](self=0x0000000173e6d340, _cmd="engage:fromViewController:", event=@"launch", viewController=0x0000000000000000) at ApptentiveInteraction.m:104
    frame #9: 0x0000000101ffbfb0 Apptentive`-[ApptentiveBackend(self=0x0000000170136260, _cmd="engageApptentiveAppEvent:", event=@"launch") engageApptentiveAppEvent:] at ApptentiveBackend+Engagement.m:82
    frame #10: 0x0000000101ffd958 Apptentive`-[ApptentiveBackend(self=0x0000000170136260, _cmd="appWillEnterForeground:", notification=@"UIApplicationWillEnterForegroundNotification") appWillEnterForeground:] at ApptentiveBackend+Metrics.m:67
    frame #11: 0x000000018b4015f4 CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
    frame #12: 0x000000018b400d08 CoreFoundation`_CFXRegistrationPost + 400
    frame #13: 0x000000018b400a84 CoreFoundation`___CFXNotificationPost_block_invoke + 60
    frame #14: 0x000000018b46f7a8 CoreFoundation`-[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1412
    frame #15: 0x000000018b34495c CoreFoundation`_CFXNotificationPost + 376
    frame #16: 0x000000018be57970 Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 68
    frame #17: 0x00000001917f4a94 UIKit`-[UIApplication _sendWillEnterForegroundCallbacks] + 232
    frame #18: 0x0000000191830524 UIKit`-[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] + 2080
    frame #19: 0x000000019182fa90 UIKit`-[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 448
    frame #20: 0x000000019181b0ec UIKit`__70-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 152
    frame #21: 0x000000019181ad68 UIKit`-[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 892
    frame #22: 0x0000000191b55360 UIKit`-[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] + 464
    frame #23: 0x000000018cfe322c FrontBoardServices`__80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke.376 + 208
    frame #24: 0x000000018d010884 FrontBoardServices`__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
    frame #25: 0x000000018d0106f0 FrontBoardServices`-[FBSSerialQueue _performNext] + 176
    frame #26: 0x000000018d010aa0 FrontBoardServices`-[FBSSerialQueue _performNextFromRunLoopSource] + 56
    frame #27: 0x000000018b41542c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
    frame #28: 0x000000018b414d9c CoreFoundation`__CFRunLoopDoSources0 + 540
    frame #29: 0x000000018b4129a8 CoreFoundation`__CFRunLoopRun + 744
    frame #30: 0x000000018b342da4 CoreFoundation`CFRunLoopRunSpecific + 424
    frame #31: 0x000000018cdad074 GraphicsServices`GSEventRunModal + 100
    frame #32: 0x00000001915fdc9c UIKit`UIApplicationMain + 208
    frame #33: 0x000000010027d3f4 AllTrailsAlpha`main(argc=3, argv=0x000000016fddb8e8) at main.m:14
    frame #34: 0x000000018a35159c libdyld.dylib`start + 4

  thread #7, name = 'gputools.smt_poll.0x17003b580'
    frame #0: 0x000000018a461314 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x000000018a3808b0 libsystem_c.dylib`nanosleep + 212
    frame #2: 0x000000018a3807d0 libsystem_c.dylib`usleep + 64
    frame #3: 0x0000000103e52670 GPUToolsCore`smt_poll_thread_entry(void*) + 136
    frame #4: 0x000000018a52968c libsystem_pthread.dylib`_pthread_body + 240
    frame #5: 0x000000018a52959c libsystem_pthread.dylib`_pthread_start + 284
    frame #6: 0x000000018a526cb4 libsystem_pthread.dylib`thread_start + 4

  thread #8, name = 'gputools.smt_poll.0x174037d20'
    frame #0: 0x000000018a461314 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x000000018a3808b0 libsystem_c.dylib`nanosleep + 212
    frame #2: 0x000000018a3807d0 libsystem_c.dylib`usleep + 64
    frame #3: 0x0000000103e52670 GPUToolsCore`smt_poll_thread_entry(void*) + 136
    frame #4: 0x000000018a52968c libsystem_pthread.dylib`_pthread_body + 240
    frame #5: 0x000000018a52959c libsystem_pthread.dylib`_pthread_start + 284
    frame #6: 0x000000018a526cb4 libsystem_pthread.dylib`thread_start + 4

  thread #9, name = 'com.apple.uikit.eventfetch-thread'
    frame #0: 0x000000018a443224 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x000000018a44309c libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018b414e90 CoreFoundation`__CFRunLoopServiceMachPort + 192
    frame #3: 0x000000018b412ae4 CoreFoundation`__CFRunLoopRun + 1060
    frame #4: 0x000000018b342da4 CoreFoundation`CFRunLoopRunSpecific + 424
    frame #5: 0x000000018be5ddb4 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
    frame #6: 0x000000018be7eb84 Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 96
    frame #7: 0x0000000191f87830 UIKit`-[UIEventFetcher threadMain] + 136
    frame #8: 0x000000018bf5b318 Foundation`__NSThread__start__ + 996
    frame #9: 0x000000018a52968c libsystem_pthread.dylib`_pthread_body + 240
    frame #10: 0x000000018a52959c libsystem_pthread.dylib`_pthread_start + 284
    frame #11: 0x000000018a526cb4 libsystem_pthread.dylib`thread_start + 4

  thread #12, name = 'com.apple.NSURLConnectionLoader'
    frame #0: 0x000000018a443224 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x000000018a44309c libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018b414e90 CoreFoundation`__CFRunLoopServiceMachPort + 192
    frame #3: 0x000000018b412ae4 CoreFoundation`__CFRunLoopRun + 1060
    frame #4: 0x000000018b342da4 CoreFoundation`CFRunLoopRunSpecific + 424
    frame #5: 0x000000018bb4fdf4 CFNetwork`+[NSURLConnection(Loader) _resourceLoadLoop:] + 404
    frame #6: 0x000000018bf5b318 Foundation`__NSThread__start__ + 996
    frame #7: 0x000000018a52968c libsystem_pthread.dylib`_pthread_body + 240
    frame #8: 0x000000018a52959c libsystem_pthread.dylib`_pthread_start + 284
    frame #9: 0x000000018a526cb4 libsystem_pthread.dylib`thread_start + 4

  thread #16
    frame #0: 0x000000018a460e1c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x000000018a528814 libsystem_pthread.dylib`_pthread_cond_wait + 640
    frame #2: 0x0000000189e51ac8 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
    frame #3: 0x000000018fcf6f08 JavaScriptCore`void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 112
    frame #4: 0x000000018fcf6e7c JavaScriptCore`bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 168
    frame #5: 0x000000018fcf6d5c JavaScriptCore`bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadEntryPoint(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*) + 36
    frame #6: 0x000000018fcf700c JavaScriptCore`void* std::__1::__thread_proxy<std::__1::tuple<void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 92
    frame #7: 0x000000018a52968c libsystem_pthread.dylib`_pthread_body + 240
    frame #8: 0x000000018a52959c libsystem_pthread.dylib`_pthread_start + 284
    frame #9: 0x000000018a526cb4 libsystem_pthread.dylib`thread_start + 4

  thread #17, name = 'WebThread'
    frame #0: 0x000000018a443224 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x000000018a44309c libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018b414e90 CoreFoundation`__CFRunLoopServiceMachPort + 192
    frame #3: 0x000000018b412ae4 CoreFoundation`__CFRunLoopRun + 1060
    frame #4: 0x000000018b342da4 CoreFoundation`CFRunLoopRunSpecific + 424
    frame #5: 0x0000000190014d3c WebCore`RunWebThread(void*) + 456
    frame #6: 0x000000018a52968c libsystem_pthread.dylib`_pthread_body + 240
    frame #7: 0x000000018a52959c libsystem_pthread.dylib`_pthread_start + 284
    frame #8: 0x000000018a526cb4 libsystem_pthread.dylib`thread_start + 4

  thread #19, name = 'AVAudioSession Notify Thread'
    frame #0: 0x000000018a443224 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x000000018a44309c libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018b414e90 CoreFoundation`__CFRunLoopServiceMachPort + 192
    frame #3: 0x000000018b412ae4 CoreFoundation`__CFRunLoopRun + 1060
    frame #4: 0x000000018b342da4 CoreFoundation`CFRunLoopRunSpecific + 424
    frame #5: 0x00000001a54ed4f4 AVFAudio`GenericRunLoopThread::Entry(void*) + 164
    frame #6: 0x00000001a5513814 AVFAudio`CAPThread::Entry(CAPThread*) + 84
    frame #7: 0x000000018a52968c libsystem_pthread.dylib`_pthread_body + 240
    frame #8: 0x000000018a52959c libsystem_pthread.dylib`_pthread_start + 284
    frame #9: 0x000000018a526cb4 libsystem_pthread.dylib`thread_start + 4

  thread #28, name = 'NetworkLoad'
    frame #0: 0x000000018a443224 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x000000018a44309c libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018b414e90 CoreFoundation`__CFRunLoopServiceMachPort + 192
    frame #3: 0x000000018b412ae4 CoreFoundation`__CFRunLoopRun + 1060
    frame #4: 0x000000018b342da4 CoreFoundation`CFRunLoopRunSpecific + 424
    frame #5: 0x000000019345c854 GeoServices`_runNetworkThread + 444
    frame #6: 0x000000018a52968c libsystem_pthread.dylib`_pthread_body + 240
    frame #7: 0x000000018a52959c libsystem_pthread.dylib`_pthread_start + 284
    frame #8: 0x000000018a526cb4 libsystem_pthread.dylib`thread_start + 4

  thread #29, queue = 'Apptentive Operation Queue :: NSOperation 0x174658e10 (QOS: DEFAULT)'
    frame #0: 0x000000018a460e1c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x000000018a528814 libsystem_pthread.dylib`_pthread_cond_wait + 640
    frame #2: 0x000000018bf34e20 Foundation`-[__NSOperationInternal _waitUntilFinished:] + 132
    frame #3: 0x000000018be5a530 Foundation`-[__NSObserver _doit:] + 232
    frame #4: 0x000000018b4015f4 CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
    frame #5: 0x000000018b400d08 CoreFoundation`_CFXRegistrationPost + 400
    frame #6: 0x000000018b400a84 CoreFoundation`___CFXNotificationPost_block_invoke + 60
    frame #7: 0x000000018b46f7a8 CoreFoundation`-[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1412
    frame #8: 0x000000018b34495c CoreFoundation`_CFXNotificationPost + 376
    frame #9: 0x000000018be57970 Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 68
    frame #10: 0x000000018de8a528 CoreTelephony`-[CTTelephonyNetworkInfo queryDataMode] + 404
    frame #11: 0x000000018de8931c CoreTelephony`-[CTTelephonyNetworkInfo init] + 340
    frame #12: 0x000000010201fec0 Apptentive`-[ApptentiveDevice updateWithCurrentDeviceValues](self=0x00000001702f6080, _cmd="updateWithCurrentDeviceValues") at ApptentiveDevice.m:154
    frame #13: 0x00000001020094a0 Apptentive`-[ApptentiveConversation checkForDiffs](self=0x0000000170113710, _cmd="checkForDiffs") at ApptentiveConversation.m:199
    frame #14: 0x000000010201694c Apptentive`-[ApptentiveConversationManager resume](self=0x00000001742e9800, _cmd="resume") at ApptentiveConversationManager.m:925
    frame #15: 0x0000000101fffad8 Apptentive`-[ApptentiveBackend setWorking:](self=0x0000000170136260, _cmd="setWorking:", working=YES) at ApptentiveBackend.m:232
    frame #16: 0x0000000101ffe97c Apptentive`-[ApptentiveBackend updateWorking](self=0x0000000170136260, _cmd="updateWorking") at ApptentiveBackend.m:145
    frame #17: 0x0000000101fff524 Apptentive`-[ApptentiveBackend startWorking](self=0x0000000170136260, _cmd="startWorking") at ApptentiveBackend.m:199
    frame #18: 0x0000000101fff228 Apptentive`__64-[ApptentiveBackend applicationWillEnterForegroundNotification:]_block_invoke((null)=<unavailable>) at ApptentiveBackend.m:186
    frame #19: 0x000000018bf36854 Foundation`__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
    frame #20: 0x000000018be7b7b0 Foundation`-[NSBlockOperation main] + 96
    frame #21: 0x000000018be6bb68 Foundation`-[__NSOperationInternal _start:] + 612
    frame #22: 0x000000018bf38bf0 Foundation`__NSOQSchedule_f + 228
    frame #23: 0x0000000103dd5a10 libdispatch.dylib`_dispatch_client_callout + 16
    frame #24: 0x0000000103de32e8 libdispatch.dylib`_dispatch_queue_serial_drain + 1140
    frame #25: 0x0000000103dd9634 libdispatch.dylib`_dispatch_queue_invoke + 852
    frame #26: 0x0000000103de5630 libdispatch.dylib`_dispatch_root_queue_drain + 552
    frame #27: 0x0000000103de539c libdispatch.dylib`_dispatch_worker_thread3 + 140
    frame #28: 0x000000018a527100 libsystem_pthread.dylib`_pthread_wqthread + 1096
    frame #29: 0x000000018a526cac libsystem_pthread.dylib`start_wqthread + 4

  thread #30
    frame #0: 0x000000018a461a88 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x000000018a5271a4 libsystem_pthread.dylib`_pthread_wqthread + 1260
    frame #2: 0x000000018a526cac libsystem_pthread.dylib`start_wqthread + 4

  thread #31
    frame #0: 0x000000018a526ca8 libsystem_pthread.dylib`start_wqthread

  thread #32, queue = 'com.alltrails.syncManager'
    frame #0: 0x000000018a4618e8 libsystem_kernel.dylib`__ulock_wait + 8
    frame #1: 0x0000000103dff300 libdispatch.dylib`_dispatch_ulock_wait + 48
    frame #2: 0x0000000103dff428 libdispatch.dylib`_dispatch_thread_event_wait_slow + 36
    frame #3: 0x0000000103de6230 libdispatch.dylib`_dispatch_barrier_sync_f_slow + 240
    frame #4: 0x000000018d7e411c CoreData`-[NSManagedObjectContext performBlockAndWait:] + 304
    frame #5: 0x000000010027ed10 AllTrailsAlpha`__30-[SyncManager performFullSync]_block_invoke((null)=<unavailable>) at SyncManager.m:192
    frame #6: 0x0000000103dd5a50 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #7: 0x0000000103dd5a10 libdispatch.dylib`_dispatch_client_callout + 16
    frame #8: 0x0000000103de32e8 libdispatch.dylib`_dispatch_queue_serial_drain + 1140
    frame #9: 0x0000000103dd9634 libdispatch.dylib`_dispatch_queue_invoke + 852
    frame #10: 0x0000000103de3810 libdispatch.dylib`_dispatch_queue_override_invoke + 404
    frame #11: 0x0000000103de5630 libdispatch.dylib`_dispatch_root_queue_drain + 552
    frame #12: 0x0000000103de539c libdispatch.dylib`_dispatch_worker_thread3 + 140
    frame #13: 0x000000018a527100 libsystem_pthread.dylib`_pthread_wqthread + 1096
    frame #14: 0x000000018a526cac libsystem_pthread.dylib`start_wqthread + 4

  thread #33
    frame #0: 0x000000018a461a88 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x000000018a5271a4 libsystem_pthread.dylib`_pthread_wqthread + 1260
    frame #2: 0x000000018a526cac libsystem_pthread.dylib`start_wqthread + 4

  thread #34, queue = 'com.apple.Pasteboard.notification-queue'
    frame #0: 0x000000018a460e1c libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x000000018a528814 libsystem_pthread.dylib`_pthread_cond_wait + 640
    frame #2: 0x000000018bf34e20 Foundation`-[__NSOperationInternal _waitUntilFinished:] + 132
    frame #3: 0x000000018be5a530 Foundation`-[__NSObserver _doit:] + 232
    frame #4: 0x000000018b4015f4 CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
    frame #5: 0x000000018b400d08 CoreFoundation`_CFXRegistrationPost + 400
    frame #6: 0x000000018b400a84 CoreFoundation`___CFXNotificationPost_block_invoke + 60
    frame #7: 0x000000018b46f7a8 CoreFoundation`-[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1412
    frame #8: 0x000000018b34495c CoreFoundation`_CFXNotificationPost + 376
    frame #9: 0x000000018be57970 Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 68
    frame #10: 0x00000001a5ce1294 Pasteboard`__67+[PBServerConnection beginListeningToPasteboardChangeNotifications]_block_invoke_2 + 300
    frame #11: 0x000000018a51dec0 libsystem_notify.dylib`___notify_dispatch_local_notification_block_invoke + 44
    frame #12: 0x0000000103dd5a50 libdispatch.dylib`_dispatch_call_block_and_release + 24
    frame #13: 0x0000000103dd5a10 libdispatch.dylib`_dispatch_client_callout + 16
    frame #14: 0x0000000103de32e8 libdispatch.dylib`_dispatch_queue_serial_drain + 1140
    frame #15: 0x0000000103dd9634 libdispatch.dylib`_dispatch_queue_invoke + 852
    frame #16: 0x0000000103de3810 libdispatch.dylib`_dispatch_queue_override_invoke + 404
    frame #17: 0x0000000103de5630 libdispatch.dylib`_dispatch_root_queue_drain + 552
    frame #18: 0x0000000103de539c libdispatch.dylib`_dispatch_worker_thread3 + 140
    frame #19: 0x000000018a527100 libsystem_pthread.dylib`_pthread_wqthread + 1096
    frame #20: 0x000000018a526cac libsystem_pthread.dylib`start_wqthread + 4

  thread #35
    frame #0: 0x000000018a461a88 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x000000018a5271a4 libsystem_pthread.dylib`_pthread_wqthread + 1260
    frame #2: 0x000000018a526cac libsystem_pthread.dylib`start_wqthread + 4

**Comment by frankus** [comment]
Our hunch is that the CoreTelephony framework that we use to allow you to target by carrier is posting a notification on the main thread, which is causing the deadlock. 

We'll release a fix on a branch for you to try out, and if it's successful push out a 4.0.2 release ASAP.

**Comment by frankus** [comment]
I've pushed a branch called [fix-deadlock](https://github.com/apptentive/apptentive-ios/tree/fix-deadlock) that hopefully does just that. 

If you're using CocoaPods you should be able to specify the branch like so: 

```
pod 'apptentive-ios', :git => 'https://github.com/apptentive/apptentive-ios.git', :branch => 'fix-deadlock'
```

Let me know if this fixes this issue and whether you run into any other problems. Thanks again for the detailed report and followup!

**Comment by matheda** [comment]
Looks like that fixed it!  I installed the updated SDK using CocoaPods as described above and then tried to reproduce the problem several different ways and was not able to.  Thanks for the quick fix, I will be on the lookout for the new version.

**Comment by frankus** [comment]
[Version 4.0.2](https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.2) is now live, so you can change back your podfile. I'll close this for now but feel free to contact us if you run into any problems with this fix.
