### ISSUE TITLE
Deadlock on iOS 4.0.1

### ISSUE THREAD

**Issue by ignazioc** [apptentive/apptentive-ios#196]
Hi, I'm using the version `4.0.1` of this library and I experience a lot of deadlock when the application comes back from the background.

I already noticed the release note of the release `4.0.2` but I'm still posting this issue because my crashlog points to a line of code that still there on `master`.

In particularly my crashlog point to this line:

https://github.com/apptentive/apptentive-ios/blob/master/Apptentive/Apptentive/Engagement/Persistence/ApptentiveBackend+Engagement.m#L107

that contains this note:

```
// FIXME: Race condition when trying to modify and save conversation from different threads
	@synchronized(conversation) {
		[conversation warmCodePoint:codePoint];
		[conversation engageCodePoint:codePoint];
	}
```

so I'm wondering...is the issue with the deadlock really fixed? why still this `FIXME` ?

**Comment by frankus** [comment]
That FIXME comment is no longer valid and should have been removed. I will make sure we do so in the next release. 

We tracked the deadlock down to a method in the CoreTelephony framework that sent a notification on the main thread which was blocked by the `@synchronized` block.
