### ISSUE TITLE
v4.0.5 Crash in -[ApptentiveBackend migrateLegacyCoreDataAndTaskQueueForConversation:conversationDirectoryPath:]

### ISSUE THREAD

**Issue by hotngui** [apptentive/apptentive-ios#202]
Here is a link to the Crashlytics details: http://crashes.to/s/48a1700e30e

**Comment by frankus** [comment]
We have released a new tag that should address this issue: https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.6-rc. 

If you are able to reproduce this crash it would be helpful to make sure it is no longer occurring.

**Comment by frankus** [comment]
We now have an [official release](https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.6) incorporating these fixes.

**Comment by frankus** [comment]
I am closing this for now. If you see additional instances of this crash with 4.0.6 or later, please re-open.
