### ISSUE TITLE
v4.0.5 Crash: ApptentivePayloadSender.m line 299

### ISSUE THREAD

**Issue by hotngui** [apptentive/apptentive-ios#203]
Crashlytics report: http://crashes.to/s/11f7ddb6c0e

**Comment by frankus** [comment]
We have released a new tag that should address this issue: https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.6-rc. 

If you are able to reproduce this crash it would be helpful to make sure it is no longer occurring.

**Comment by hotngui** [comment]
Unfortunately the podspec not published, so build build guy says he cannot access it in our build process.

On Sep 21, 2017, at 11:33 AM, Frank Schmitt <notifications@github.com<mailto:notifications@github.com>> wrote:


We have released a new tag that should address this issue: https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.6-rc.

If you are able to reproduce this crash it would be helpful to make sure it is no longer occurring.

**Comment by frankus** [comment]
I'm not sure whether this works with your build system in particular, but CocoaPods will let you specify a repository and branch:

```
pod 'apptentive-ios', :git => 'https://github.com/apptentive/apptentive-ios.git', :branch => 'v4.0.6-rc'
```

If that doesn't work, we will be doing a general release that incorporates this fix in the near future.

**Comment by hotngui** [comment]
We are familiar with how cocoapods work, but not supposed to grab unpublished branches.

Any idea when you’ll have it ready for publishing?

On Sep 22, 2017, at 2:07 PM, Frank Schmitt <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure whether this works with your build system in particular, but CocoaPods will let you specify a repository and branch:

pod 'apptentive-ios', :git => 'https://github.com/apptentive/apptentive-ios.git', :branch => 'v4.0.6-rc'


If that doesn't work, we will be doing a general release that incorporates this fix in the near future.

**Comment by frankus** [comment]
We now have an [official release](https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.6) incorporating these fixes.

**Comment by frankus** [comment]
I am closing this for now. If you see additional instances of this crash on 4.0.6 or later, please re-open.
