### ISSUE TITLE
v4.0.5 Crash in ApptentiveRequestOperation.m, line 142

### ISSUE THREAD

**Issue by Taarna** [apptentive/apptentive-ios#204]
We're using Xcode 9, Swift 4.0 and Apptentive SDK 4.0.5. 

The app crashes if multi-threading assertions are enabled.

![screen shot 2017-09-26 at 14 58 34](https://user-images.githubusercontent.com/4928442/30861526-3e6a005a-a2cb-11e7-8dc1-9bc6686f62f7.png)

**Comment by frankus** [comment]
Thanks for the report. We are aware of this issue and are preparing a release that fixes it. I'll update this when we have released a fix.

**Comment by frankus** [comment]
We now have an [official release](https://github.com/apptentive/apptentive-ios/releases/tag/v4.0.6) including a fix to the Core Data concurrency errors.

**Comment by Taarna** [comment]
It doesn't crash anymore. Thank you! :)
