### ISSUE TITLE
iPad crash in ApptentiveInteractionTextModalController

### ISSUE THREAD

**Issue by carllindberg** [apptentive/apptentive-ios#205]
It looks like ApptentiveInteractionTextModalController can create a UIAlertViewController with an alertType of UIAlertControllerStyleActionSheet, but it is not setting the sourceView and sourceRect on the corresponding UIPopoverPresentationController on iPad devices.  That will result in a crash, since action sheets are popovers there.

We got this in version 3.5.1, but looking at the code, while changed I think it still has this issue.

> NSGenericException: Your application has presented a UIAlertController (<UIAlertController: 0x15fdabd30>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem. If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.

```
  | 0 | CoreFoundation 0x000000018acc2fe0 __exceptionPreprocess + 120
  | 1 | libobjc.A.dylib 0x0000000189724538 objc_exception_throw + 52
  | 2 | UIKit 0x0000000191832be8 -[UIPopoverPresentationController presentationTransitionWillBegin] + 2780
  | 3 | UIKit 0x00000001911400d4 __71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke + 1968
  | 4 | UIKit 0x000000019113de04 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 448
... [UIKit frames -- looks like a asynchronous block raises the exception]
```

I can't positively attribute that to Apptentive, but we don't have an alert controller on the page it's crashing on, and we do have an Apptentive trigger.  And, this was the only place in our code or Apptentive's where I could see UIAlertControllerStyleActionSheet being used without setting a sourceView.

**Comment by frankus** [comment]
I'll definitely take a look at this. The SDK should never reach that code path because as far as I'm aware the `layout` property of the configuration dictionary is never set to `bottom`. 

Are you using an integration method where you could temporarily edit the Apptentive SDK source code to disable that code path (e.g. change `UIAlertControllerStyleActionSheet` to `UIAlertControllerStyleAlert`) and try and reproduce the issue?

Since it isn't practical for us to supply a source rect, I will make a note to disable that code path entirely on iPad devices in our next release.

**Comment by carllindberg** [comment]
It is hard to debug the Apptentive path.  However, we disabled the alert completely in the Apptentive config -- though it may have been re-enabled with an iPhone check -- and the crashes have slowed but not stopped, meaning we do have another issue in our code somewhere.  May be a situation where our code has been fortuitously changed since the branch which is in production.  I am suspicious there may be a path where a view was being passed down as nil in our code,  which is as good as not setting it.  It's not possible in our current codebase, but maybe it was earlier.

Anyways, any use of ActionSheet should be protected by setting a sourceView.  You could always use the presenting view controller's view, with the bottom-center edge and a size of {1,1}.  But, if you suspect that this code path is impossible in Apptentive, you may well be correct, in which case this is a minor code issue but not a real bug.  Sorry for the false alarm in that case ;-)

**Comment by frankus** [comment]
The code that was theoretically capable of displaying a text modal (Note) in action sheet mode has been removed in 4.1.0.
