### ISSUE TITLE
Ad Hoc build: Failed to verify bitcode in Apptentive.framework/Apptentive

### ISSUE THREAD

**Issue by JamieScanlon** [apptentive/apptentive-ios#208]
Steps:
- Archive a project that includes the Apptentive Framework
- Select Export
- Select Ad Hoc

You will see this error which seems to be a result of the bitcode compilation differences between normal builds and archived builds. More details about the differences between the two can be found in this thread: https://github.com/Carthage/Carthage/issues/535

**Comment by frankus** [comment]
Thank you for the report and sorry for the radio silence on my end. 

I've built the framework for the 5.0.0 version using `archive` for the `iphoneos` destination, as suggested in the thread you linked to. 

We're doing some testing on our end as well, but if you have a sec please let me know if it works for you.

**Comment by frankus** [comment]
I fell victim to this as well, but it looks like you have to follow the [considerably-more-involved instructions for an iOS, watchOS or tvOS project](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) or bitcode will not be built correctly. This involves not using the "Embedded Binaries" section, but instead running a custom Run Script build script phase to your app target. 

<img width="484" alt="screen shot 2017-12-19 at 10 04 06 pm" src="https://user-images.githubusercontent.com/50842/34193447-9a97b23a-e508-11e7-8952-b4d3bb8a2dbe.png">

I'm closing this for now, but please let me know if you run into any further issues.
