### ISSUE TITLE
CocoaPods install guide

### ISSUE THREAD

**Issue by StevenMyers32** [apptentive/apptentive-ios#209]
Just a suggestion to update the currently linked CocoaPods guide in the README. I had trouble installing via that guide.  I needed to set the NO_USE_FRAMEWORKS flag. 

Red linked me this guide: https://learn.apptentive.com/knowledge-base/ios-integration-reference/#cocoapods

It seems to be more detailed than the current linked guide, which doesn't have info on the frameworks flag. 

Thanks!

**Comment by frankus** [comment]
Thanks for the heads up! I've updated the guide linked to from the README and added a checklist item to make sure we keep it up to date.
