### ISSUE TITLE
Rating dialog submit button disabled

### ISSUE THREAD

**Issue by spraveenk91** [apptentive/apptentive-ios#213]
Hello Apptentive team,

I am using below version of apptentive into my iOS application. 

> pod 'apptentive-ios' , '3.5.0'

When, i am getting the rating dialog in my iPhone with version **11.2.6** The rating dialogs are being disabled. Please, find the attached image for the reference.

![ratingedited](https://user-images.githubusercontent.com/3426723/39291325-4442e7fe-4950-11e8-80f3-453bbca811ef.png)

What could be the reason for this disabled state for the submit button?

**Comment by wooster** [comment]
Is this in an app downloaded from the App Store, or a development version?

From [Apple's docs](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview):

> When you call this method while your app is still in development mode, a rating/review request view is always displayed so that you can test the user interface and experience. However, this method has no effect when you call it in an app that you distribute using TestFlight.

[This StackOverflow thread](https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review) may also be helpful.

**Comment by spraveenk91** [comment]
My mistake, yes its clearly mention in the apptentive [documentation](https://learn.apptentive.com/knowledge-base/requesting-ratings-on-ios/) as below:

<img width="673" alt="screen shot 2018-04-27 at 6 01 40 pm" src="https://user-images.githubusercontent.com/3426723/39362724-120c95f0-4a45-11e8-8c9d-8e776b0a23ae.png">
