### ISSUE TITLE
Hang in iOS SDK

### ISSUE THREAD

**Issue by matheda** [apptentive/apptentive-ios#222]
We have been getting reports from the field that users are experiencing UI hangs followed by app shutdowns.  We have been trying to track this down, and finally added a watchdog feature that pings the UI queue.  If it does not respond in a given amount of time we intentionally crash the app so that we can get a stack trace of what is going on.  

Looking through the results, we have found that the issue almost always involves the Apptentive SDK in one of two states.

We were running on 5.2.1 and tried backing down a version but still had the same issues, so we are not sure when this behavior started happening.  It is happening on various types of devices running various versions of iOS.

### State One
**Main queue:** Non-Apptentive code
**Background queue:** Non-Apptentive code attempting to perform a Core Data operation using performBlockAndWait
**Background queue:** ApptentiveSerialRequest 

![screen shot 2018-10-15 at 5 30 02 am](https://user-images.githubusercontent.com/1895008/46942561-99fde000-d03b-11e8-90bf-45b3f56324d3.png)

### State two  (Less Frequent) 
**Main queue:** ApptentiveBackend code 
**Background queue:** ApptentiveLogFileWriteTask code

Here is the full stack for the second scenario:

Crashed: WatchDog
EXC_BREAKPOINT 0x00000001033f6480

Crashed: WatchDog
0  libswiftCore.dylib             0x1033f6480 _stdlib_destroyTLS + 207848
1  libswiftCore.dylib             0x10325e10c (Missing)
2  AllTrails                      0x1016e0d70 closure #1 in WatchdogService.init() (WatchdogService.swift:19)
3  Watchdog                       0x10317cc50 PingThread.main() (Watchdog.swift:76)
4  Watchdog                       0x10317cd0c @objc PingThread.main() (<compiler-generated>)
5  Foundation                     0x183ca1efc __NSThread__start__ + 1040
6  libsystem_pthread.dylib        0x182e7d220 _pthread_body + 272
7  libsystem_pthread.dylib        0x182e7d110 _pthread_body + 290
8  libsystem_pthread.dylib        0x182e7bb10 thread_start + 4
com.apple.main-thread

com.apple.main-thread
0  libsystem_kernel.dylib         0x182cbbde8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x182cbbc60 mach_msg + 72
2  IOKit                          0x183523bb8 io_connect_method + 416
3  IOKit                          0x1834c0038 IOConnectCallMethod + 232
4  MobileKeyBag                   0x185a06948 _get_device_state + 128
5  MobileKeyBag                   0x1859edf64 _get_device_lock_state + 224
6  MobileKeyBag                   0x1859ee0ec MKBGetDeviceLockState + 36
7  UIKit                          0x18cf4c5a4 -[UIApplication isProtectedDataAvailable] + 16
8  Apptentive                     0x1027beb90 -[ApptentiveBackend initWithApptentiveKey:signature:baseURL:storagePath:operationQueue:] (ApptentiveBackend.m:89)
9  Apptentive                     0x1027a8fc4 -[Apptentive initWithConfiguration:] (Apptentive.m:148)
10 Apptentive                     0x1027a91d0 +[Apptentive registerWithConfiguration:] (Apptentive.m:172)
11 AllTrails                      0x10147454c -[EngagementService prepareForUseWithApplication:launchOptions:] (EngagementService.m:77)
12 AllTrails                      0x1013ed040 -[AppDelegate application:didFinishLaunchingWithOptions:] (AppDelegate.m:78)
13 UIKit                          0x18ce65dbc -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 408
14 UIKit                          0x18ce651c4 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3484
15 UIKit                          0x18ce325e0 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1680
16 UIKit                          0x18d462b1c __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 784
17 UIKit                          0x18ce31dd0 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 160
18 UIKit                          0x18ce31c6c -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 240
19 UIKit                          0x18ce30afc -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 724
20 UIKit                          0x18dac684c __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 296
21 UIKit                          0x18ce301ec -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 432
22 UIKit                          0x18d8abac8 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 220
23 UIKit                          0x18d9f9bf8 _performActionsWithDelayForTransitionContext + 112
24 UIKit                          0x18ce2fc0c -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 248
25 UIKit                          0x18ce2f5a8 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 368
26 UIKit                          0x18ce2c5e0 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 540
27 UIKit                          0x18ce2c330 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 364
28 FrontBoardServices             0x185a58470 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 364
29 FrontBoardServices             0x185a60d6c __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 224
30 libdispatch.dylib              0x182b48a60 _dispatch_client_callout + 16
31 libdispatch.dylib              0x182b50170 _dispatch_block_invoke_direct$VARIANT$mp + 224
32 FrontBoardServices             0x185a8c878 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 36
33 FrontBoardServices             0x185a8c51c -[FBSSerialQueue _performNext] + 404
34 FrontBoardServices             0x185a8cab8 -[FBSSerialQueue _performNextFromRunLoopSource] + 56
35 CoreFoundation                 0x1831ff404 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
36 CoreFoundation                 0x1831fec2c __CFRunLoopDoSources0 + 276
37 CoreFoundation                 0x1831fc79c __CFRunLoopRun + 1204
38 CoreFoundation                 0x18311cda8 CFRunLoopRunSpecific + 552
39 GraphicsServices               0x185102020 GSEventRunModal + 100
40 UIKit                          0x18d13c758 UIApplicationMain + 236
41 AllTrails                      0x101493cf0 main (main.m:14)
42 libdyld.dylib                  0x182badfc0 start + 4
Thread #1

Thread
0  libsystem_kernel.dylib         0x182cddd78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x182e7c0a0 _pthread_wqthread + 1420
2  libsystem_pthread.dylib        0x182e7bb08 start_wqthread + 4
com.google.fira.worker

com.google.fira.worker
0  libsystem_kernel.dylib         0x182cbe0e4 fsync + 8
1  libsqlite3.dylib               0x1836b5650 sqlite3_free_table + 59012
2  libsqlite3.dylib               0x1836c0980 sqlite3_randomness + 2620
3  libsqlite3.dylib               0x1836b4d94 sqlite3_free_table + 56776
4  libsqlite3.dylib               0x1836a1828 sqlite3_value_text + 22032
5  libsqlite3.dylib               0x183670bd8 sqlite3_finalize + 4128
6  libsqlite3.dylib               0x18369a7b0 sqlite3_step + 57524
7  libsqlite3.dylib               0x18368d314 sqlite3_step + 3096
8  libsqlite3.dylib               0x1836587d0 sqlite3_exec + 520
9  AllTrails                      0x10197f1b8 -[APMSqliteStore endTransaction] + 4318572984
10 AllTrails                      0x10197ee70 -[APMSqliteStore performTransaction:] + 4318572144
11 AllTrails                      0x10195aad0 -[APMMeasurement setUserAttributeOnWorkerQueue:] + 4318423760
12 AllTrails                      0x10196b660 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4318492256
13 libdispatch.dylib              0x182b48aa0 _dispatch_call_block_and_release + 24
14 libdispatch.dylib              0x182b48a60 _dispatch_client_callout + 16
15 libdispatch.dylib              0x182b529b4 _dispatch_queue_serial_drain$VARIANT$mp + 608
16 libdispatch.dylib              0x182b532fc _dispatch_queue_invoke$VARIANT$mp + 336
17 libdispatch.dylib              0x182b53cc8 _dispatch_root_queue_drain_deferred_wlh$VARIANT$mp + 340
18 libdispatch.dylib              0x182b5c098 _dispatch_workloop_worker_thread$VARIANT$mp + 668
19 libsystem_pthread.dylib        0x182e7be70 _pthread_wqthread + 860
20 libsystem_pthread.dylib        0x182e7bb08 start_wqthread + 4
com.apple.uikit.eventfetch-thread

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x182cbbde8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x182cbbc60 mach_msg + 72
2  CoreFoundation                 0x1831fee40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1831fc908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x18311cda8 CFRunLoopRunSpecific + 552
5  Foundation                     0x183b91674 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x183b914dc -[NSRunLoop(NSRunLoop) runUntilDate:] + 84
7  UIKit                          0x18ce21768 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x183ca1efc __NSThread__start__ + 1040
9  libsystem_pthread.dylib        0x182e7d220 _pthread_body + 272
10 libsystem_pthread.dylib        0x182e7d110 _pthread_body + 290
11 libsystem_pthread.dylib        0x182e7bb10 thread_start + 4
Thread #2

Thread
0  libsystem_kernel.dylib         0x182cddd78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x182e7beb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x182e7bb08 start_wqthread + 4
Thread #3

Thread
0  libsystem_pthread.dylib        0x182e7bb04 start_wqthread + 122
Thread #4

Thread
0  libsystem_kernel.dylib         0x182cddd78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x182e7beb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x182e7bb08 start_wqthread + 4
Log Queue (QOS: UNSPECIFIED)

Log Queue (QOS: UNSPECIFIED)
0  libsystem_kernel.dylib         0x182cbe0e4 fsync + 8
1  Foundation                     0x183c48b94 -[NSConcreteFileHandle synchronizeFile] + 56
2  Apptentive                     0x1027ecdfc -[ApptentiveLogFileWriteTask execute] (ApptentiveLogFileWriteTask.m:64)
3  Apptentive                     0x1027db584 -[ApptentiveDispatchTask executeTask] (ApptentiveDispatchTask.m:26)
4  Apptentive                     0x1027df61c -[ApptentiveGCDDispatchQueue dispatchTaskGuarded:] (ApptentiveGCDDispatchQueue.m:55)
5  Foundation                     0x183c7ee88 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
6  Foundation                     0x183bc08d0 -[NSBlockOperation main] + 72
7  Foundation                     0x183bbfcac -[__NSOperationInternal _start:] + 848
8  libdispatch.dylib              0x182b48a60 _dispatch_client_callout + 16
9  libdispatch.dylib              0x182b50170 _dispatch_block_invoke_direct$VARIANT$mp + 224
10 libdispatch.dylib              0x182b48a60 _dispatch_client_callout + 16
11 libdispatch.dylib              0x182b50170 _dispatch_block_invoke_direct$VARIANT$mp + 224
12 libdispatch.dylib              0x182b5005c dispatch_block_perform$VARIANT$mp + 104
13 Foundation                     0x183c80750 __NSOQSchedule_f + 376
14 libdispatch.dylib              0x182b48a60 _dispatch_client_callout + 16
15 libdispatch.dylib              0x182b50e94 _dispatch_continuation_pop$VARIANT$mp + 424
16 libdispatch.dylib              0x182b4f7cc _dispatch_async_redirect_invoke$VARIANT$mp + 604
17 libdispatch.dylib              0x182b55cac _dispatch_root_queue_drain + 588
18 libdispatch.dylib              0x182b559fc _dispatch_worker_thread3 + 120
19 libsystem_pthread.dylib        0x182e7bfac _pthread_wqthread + 1176
20 libsystem_pthread.dylib        0x182e7bb08 start_wqthread + 4
Thread #5

Thread
0  libsystem_kernel.dylib         0x182cddd78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x182e7beb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x182e7bb08 start_wqthread + 4
Thread #6

Thread
0  libsystem_kernel.dylib         0x182cddd78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x182e7beb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x182e7bb08 start_wqthread + 4
Thread #7

Thread
0  libsystem_kernel.dylib         0x182cddd78 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x182e7beb4 _pthread_wqthread + 928
2  libsystem_pthread.dylib        0x182e7bb08 start_wqthread + 4
com.apple.NSURLConnectionLoader

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x182cbbde8 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x182cbbc60 mach_msg + 72
2  CoreFoundation                 0x1831fee40 __CFRunLoopServiceMachPort + 196
3  CoreFoundation                 0x1831fc908 __CFRunLoopRun + 1568
4  CoreFoundation                 0x18311cda8 CFRunLoopRunSpecific + 552
5  CFNetwork                      0x183a2a6e0 -[__CoreSchedulingSetRunnable runForever] + 220
6  Foundation                     0x183ca1efc __NSThread__start__ + 1040
7  libsystem_pthread.dylib        0x182e7d220 _pthread_body + 272
8  libsystem_pthread.dylib        0x182e7d110 _pthread_body + 290
9  libsystem_pthread.dylib        0x182e7bb10 thread_start + 4

com.twitter.crashlytics.ios.MachExceptionServer
0  AllTrails                      0x101897fc0 CLSProcessRecordAllThreads (CLSProcess.c:376)
1  AllTrails                      0x101898480 CLSProcessRecordAllThreads (CLSProcess.c:407)
2  AllTrails                      0x101887cac CLSHandler (CLSHandler.m:26)
3  AllTrails                      0x101883084 CLSMachExceptionServer (CLSMachException.c:446)
4  libsystem_pthread.dylib        0x182e7d220 _pthread_body + 272
5  libsystem_pthread.dylib        0x182e7d110 _pthread_body + 290
6  libsystem_pthread.dylib        0x182e7bb10 thread_start + 4

**Comment by weeeBox** [comment]
Hi @matheda,

Sorry for the issue. We'll take a look asap!

**Comment by frankus** [comment]
We're reviewing a fix for state one, and plan to start on state two tomorrow.

**Comment by matheda** [comment]
Great, thank you for the quick response!

**Comment by dchankhour** [comment]
We are also still seeing  the issue on our App

**Comment by weeeBox** [comment]
We've prepared the fix and currently testing it. Would be released early next week.

**Comment by matheda** [comment]
Thank you!

**Comment by frankus** [comment]
We've released the 5.2.2 update that should address this issue. Please let us updated on whether you continue to see the issue with 5.2.2. Thanks!

**Comment by matheda** [comment]
Awesome, thank you as always for the quick response!  I am going to make an internal build today with the update so we can do some testing.  It will most likely go out to users the week after next.
