### ISSUE TITLE
Crash in iOS SDK 5.2.2 - ApptentiveSerialRequest enqueuePayload: forConversation: usingAuthToken: inContext:

### ISSUE THREAD

**Issue by SarithaPar** [apptentive/apptentive-ios#226]
Our app is crashing while enqueuePayload from ApptentiveSerialRequest.m. We are using appetitive_ios_framework-5.2.2.

```[ApptentiveSerialRequest enqueuePayload:forConversation:usingAuthToken:inContext:]_block_invoke (ApptentiveSerialRequest.m:119)```

Here is more detail about the crash:

```
#0Crashed: NSManagedObjectContext 0x281ce7ed0EXC_BREAKPOINT 0x0000000106cb21a4 Raw Text
--
0 | libswiftCore.dylib | specialized _assertionFailure(_:_:file:line: flags:) + 42360
13 | CoreData | _sharedIMPL_setvfk_core + 208
14 | Apptentive | ApptentiveSerialRequest.m line 119__83+[ApptentiveSerialRequest enqueuePayload:forConversation:usingAuthToken:inContext:]_block_invoke
15 | CoreData | developerSubmittedBlockToNSManagedObjectContextPerform + 156
18 | CoreData | -[NSManagedObjectContext performBlockAndWait:] + 304
19 | Apptentive | ApptentiveSerialRequest.m line 132+[ApptentiveSerialRequest enqueuePayload:forConversation:usingAuthToken:inContext:]
20 | Apptentive | ApptentiveConversationManager.m line 655-[ApptentiveConversationManager conversationAppReleaseOrSDKDidChange:]
21 | Apptentive | ApptentiveConversation.m line 191-[ApptentiveConversation checkForDiffs]
22 | Apptentive | ApptentiveConversationManager.m line 391-[ApptentiveConversationManager handleConversationStateChange:]
23 | Apptentive | ApptentiveConversationManager.m line 115-[ApptentiveConversationManager loadActiveConversation]
24 | Apptentive | ApptentiveBackend.m line 290-[ApptentiveBackend startUp]
25 | Apptentive | ApptentiveGCDDispatchQueue.m line 55-[ApptentiveGCDDispatchQueue dispatchTaskGuarded:]
26 | Foundation | __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
37 | libsystem_pthread.dylib | start_wqthread + 4

```

**Comment by frankus** [comment]
Hi @SarithaPar, thank you for the report. We will take a look at this as soon as we can. In the meantime, could you let us know if this is something you are able to reproduce on demand, or something that occasionally occurs during testing, or have you received a report from a customer or third-party crash reporting tool? If it's the latter, do you have any additional information on the device where the crash occurred?

Thanks!

**Comment by SarithaPar** [comment]
Hi @frankus , we are observing this crash from third-party tool and unable to reproduce at our end. This is generic crash and observed in all iOS device including OS version 10/11/12.

Along with this crash we also getting crashes from [ApptentiveRequestOperation initWithURLRequest:delegate:dataSource:]. Which is also top crash in our reporting tool.


They could be related or not. Let me know if we have to create ticket from second one separately.

Below is the crash detail related to **ApptentiveRequestOperation**:

```
0 | libswiftCore.dylib | specialized _assertionFailure(_:_:file:line: flags:) + 42360
10 | Foundation | -[NSOperation init] + 352
11 | Apptentive | ApptentiveRequestOperation.m line 36-[ApptentiveRequestOperation initWithURLRequest:delegate:dataSource:]
12 | Apptentive | ApptentiveClient.m line 113-[ApptentiveClient requestOperationWithRequest:token:delegate:]
13 | Apptentive | ApptentivePayloadSender.m line 130__70-[ApptentivePayloadSender createOperationsForQueuedRequestsInContext:]_block_invoke.50
14 | CoreData | developerSubmittedBlockToNSManagedObjectContextPerform + 156
17 | CoreData | -[NSManagedObjectContext performBlockAndWait:] + 304
18 | Apptentive | ApptentivePayloadSender.m line 139__70-[ApptentivePayloadSender createOperationsForQueuedRequestsInContext:]_block_invoke
19 | Foundation | __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
30 | libsystem_pthread.dylib | start_wqthread + 4
```

Regards, Saritha

**Comment by frankus** [comment]
Hi @SarithaPar, does it look like the devices seeing the crash are under memory pressure? 

The main difference between the version you are on and the previous version is that all Core Data activity in our SDK has been moved off the main thread, so things like migrations and loading the database happen concurrently with other app launch activities (based on the stack trace, it looks as though this is occurring shortly after app launch). 

Please do create another issue for the other crash that you are seeing.

**Comment by frankus** [comment]
Does your app use Apptentive's Message Center feature?

**Comment by SarithaPar** [comment]
Hi @frankus,

• We cannot reproduce this. It is our top crash but something that is very rare ( we just have lots of users )
• There is no memory pressure, as this is early in startup.
• would you be interested in full stack logs?

we are starting Apptentive service very early in our startup, Is there any downside in deferring this later until we are fully up?

**Comment by frankus** [comment]
I think full stack logs would be a good next step. You can either paste them here or email us (sdks at apptentive dot com). Thank you!

**Comment by SarithaPar** [comment]
Shared via email

**Comment by frankus** [comment]
Thanks, I just received it. This looks suspiciously similar to a bug reported in Swift 4: https://bugs.swift.org/browse/SR-6795. 

If that is the case there probably isn't much we can do on our end, but rather you may need to replace any Swift KVO use in your app with Objective-C or propagate notifications another way.
