### ISSUE TITLE
Failure to compile using xcodebuild

### ISSUE THREAD

**Issue by mhriess** [apptentive/apptentive-ios#229]
apptentive-ios version 5.2.3
xcode version 10.1

We have a react native project that integrates the Apptentive iOS SDK through cocoa pods. `xcodebuild` fails while deploying the app via from local machines for some of our teammates with the following output. We have been so far unable to determine what the difference is between the successful and failing machines. At one point, reducing the iOS Deployment Target from 10.3 to 9.0 temporarily solved the problem for some folks, but it has since resurfaced.

```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFontDescriptor.h:20:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFontTraits.h:12:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTDefines.h:12:10: fatal error: could not build module 'Darwin'
#include <Availability.h>
 ~~~~~~~~^
1 error generated.
While building module 'UIKit' imported from ../../../ios/Pods/apptentive-ios/Apptentive/Apptentive/Apptentive.h:9:
While building module 'FileProvider' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/NSFileProviderExtension.h:15:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/FileProvider.framework/Headers/FileProvider.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/FileProvider.framework/Headers/NSFileProviderDomain.h:8:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
1 error generated.
21 errors generated.
In file included from /Users/michaelriess/go/src/github.com/scriptdash/clients/native/node_modules/react-native-apptentive-module/ios/RNApptentiveModule/ApptentiveModule.m:9:
../../../ios/Pods/apptentive-ios/Apptentive/Apptentive/Apptentive.h:9:9: fatal error: could not build module 'UIKit'
#import <UIKit/UIKit.h>
 ~~~~~~~^
While building module 'UserNotifications' imported from ../../../ios/Pods/apptentive-ios/Apptentive/Apptentive/Apptentive.h:10:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UserNotifications.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/NSString+UserNotifications.h:8:9: fatal error: could not build module 'Foundation'
#import <Foundation/Foundation.h>
 ~~~~~~~^
1 error generated.
23 errors generated.
```

Any help greatly appreciated!

**Comment by frankus** [comment]
Apologies for the delay in responding, we had a bit of a breakdown in our triage process!

Just to be clear, you're using `react native link` to incorporate the Apptentive bridge code, and then using CocoaPods to incorporate the Apptentive iOS SDK?

**Comment by mhriess** [comment]
No worries, thanks Frank!

We are using CocoaPods to incorporate the SDK, but we have the bridge code [linked manually](https://facebook.github.io/react-native/docs/linking-libraries-ios#step-1-1) rather than through `react native link`.

**Comment by frankus** [comment]
I haven't been able to reproduce this error, but there are references to Xcode 10's new build system leading to errors like this. Can you try selecting the project, choosing File > Workspace Settings… and setting it to use the legacy build system?

**Comment by frankus** [comment]
Did changing the build system allow you to build successfully?

**Comment by mhriess** [comment]
Hi @frankus sorry for the radio silence here. We use the legacy build system by default, but the error appears to be unrelated. Our only solution continues to be (re)setting the Apptentive library's deployment target to 9.0.

**Comment by CaseyApptentive** [comment]
Hi @mhriess, thanks for circling back. I'll take a closer look with my team. 

To be sure: is this blocking you from release, or is it more of a hinderance? Either way, we'll look for a solution, but this will help us prioritize. 

Also, which app are you working on this for? Let me know and I'll take a look at our backend to make sure everything is in line for that app. 

Thanks!
