### ISSUE TITLE
404 Page Not found after changing to new Key & signature

### ISSUE THREAD

**Issue by ganderson2** [apptentive/apptentive-ios#230]
Our iOS app moved to a new Apptentive account.
We rebuilt the iOS app with the new key & signature. And upgraded to SDK v5.1.2 from v5.0.2

The app then got  "error":"page not found"
POST https://api.apptentive.com/conversations/xxxxxxxxxx/events failed with error after 1.06797 sec (Error Domain=com.apptentive.http Code=404 "Client error" UserInfo={NSErrorFailingURLKey=https://api.apptentive.com/conversations/xxxxxxxxxxx/events

We deleted the app from the iPad.
Re-installed the app.
And the error went away and the Apptentive link worked.

Our app appears to hold on to our old Apptentive connection information.
Not all of our users experience the problem.
We would like to avoid uninstalling and reinstalling the app.
Is there something we can do to remedy this?

Thanks,
Greg

**Comment by frankus** [comment]
When the SDK is registered at app launch, it looks for data saved from a previous app launch and will attempt to use that data to reconnect to the same session (what internally we call a "conversation"). These sessions are pinned to a particular app key and signature. When you change the app key and/or signature, the server notices that it doesn't match the current session and sends back a 404. 

We typically recommend deleting and reinstalling the app to clear the session, but you can also delete just the Apptentive data directory in the device/simulator's Application Support directory. It's called `com.apptentive.feedback`, and on any recent (post-4.0 SDK) that will wipe the SDK state so you can start a new session with a new API key and signature.
