### ISSUE TITLE
Cannot able to change Submit button UI and radio button color

### ISSUE THREAD

**Issue by suman-cdl** [apptentive/apptentive-ios#231]
Hi, I am using SDK 5.2.3 and I can not able to change Submit button text and border also not able to change radio button color.
![test](https://user-images.githubusercontent.com/34672940/56804211-e7c98100-67f2-11e9-98d0-95b7d90786e8.png)

**Comment by frankus** [comment]
The submit button and radio buttons automatically pick up the tintColor property of the view controller/window. 

The easiest way to change it is to use UIAppearance, for example add the following when your app launches:

```
UIView.appearance(whenContainedInInstancesOf: ApptentiveNavigationController.self).tintColor = UIColor.red
```

**Comment by frankus** [comment]
I'll make a note to call this out a bit more clearly in our styling documentation.
