### ISSUE TITLE
Xcode 11 beta 3 - UIWebView error when trying to run iOS app as macOS app

### ISSUE THREAD

**Issue by MihaiPantiru** [apptentive/apptentive-ios#234]
We try to port an iOS app which uses Apptentive iOS SDK to run on macOS 10.15 as an iPad app.

Compiling the app on macOS throws an Apptentive SDK error: 
`Pods/apptentive-ios/Apptentive/Apptentive/Apptentive.storyboard:MnL-J4-fWD: error: UIWebView is unavailable when building for Mac. [6]`

IDE: Xcode 11 beta 3
OS: macOS 10.15 beta 3

**Comment by weeeBox** [comment]
Hi @MihaiPantiru, we don't support MacOS builds at this time. Please, consider adding Apptentive SDK dependency only for iOS-related targets. Please, let us know if you have any questions!

**Comment by MihaiPantiru** [comment]
Hi @weeeBox. Technically, the new feature added in Xcode 11 is running iOS apps on macOS so is an iOS target. But since UIWebView is deprecated (https://developer.apple.com/documentation/uikit/uiwebview) any chances you would migrate to WKWebView in the near future? Thanks a lot!

**Comment by weeeBox** [comment]
Thanks for clarifying - we'll take a closer look and get back to you!

**Comment by frankus** [comment]
Right now it looks like we would have to drop iOS 9 & 10 support to update to WKWebView (NSCoding was broken for WKWebView prior to iOS 11), or phase out the upgrade dialog feature, or construct its view programmatically. We'll have a discussion with our product team to figure out next steps.

**Comment by frankus** [comment]
We have removed references to UIWebView in release [5.2.5](https://github.com/apptentive/apptentive-ios/releases/tag/v5.2.5).  We aren't currently supporting Catalyst apps, but are definitely keeping an eye on this for the future.
