### ISSUE TITLE
Xcode 10.3 apptentive-ios (5.2.4) ".../Pods/apptentive-ios/Apptentive/Apptentive/Apptentive.storyboard:-1: Compilation Failed."

### ISSUE THREAD

**Issue by pbonneville** [apptentive/apptentive-ios#235]
Anyone else experiencing this error in Xcode 10.3?:

".../Pods/apptentive-ios/Apptentive/Apptentive/Apptentive.storyboard:-1: Compilation Failed."

I've updated to the latest Pod but am now unable to build my app due to the Apptentive Cocoapod.

**Comment by frankus** [comment]
Thanks for the report. We're taking a look.

**Comment by pbonneville** [comment]
Just to follow up here, it seems upgrading my OS to Mojave 10.14.6 may have fixed the issue with 10.3

**Comment by CaseyApptentive** [comment]
Thanks for the update, @pbonneville !

It sounds like you're still using Xcode 10.3 as well when your OS is on Mojave 10.14.6?

Appreciate your help. I want to be sure to document this if there's an issue with particular versions.

**Comment by pbonneville** [comment]
Correct. The issue for me occurred when my system auto updated to Xcode 10.3 before I updated to Mojave 10.14.6. Not sure if it was related or not, but the issue when away after the OS update.

**Comment by CaseyApptentive** [comment]
Much appreciated, @pbonneville. Let me know if there's anything else we can do to help.
