### ISSUE TITLE
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by aanelson** [apptentive/apptentive-ios#236]
Hello, we have recently gotten this message with the last release of our app.  The only UIWebkit dependency in our app is in apptentive.   

> We identified one or more issues with a recent delivery for your app, "our app" 0.15.0 (4804). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you've corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by frankus** [comment]
Thanks for the report. We're aware of this and will be releasing an update to address this within the next few days.

**Comment by spraveenk91** [comment]
Apptentive team has released a new version [5.2.5](https://github.com/apptentive/apptentive-ios/releases/tag/v5.2.5) for this issue.

**Comment by frankus** [comment]
Closing this issue because as @spraveenk91 mentioned, we have released an update that removes references to UIWebView (and supports dark mode).
