### ISSUE TITLE
Add delegate functions for user interactions

### ISSUE THREAD

**Issue by yangchen-acc** [apptentive/apptentive-ios#238]
Hi Team, we're trying to send log file to apptentive only when user submits a message from the messageCenter, is there a way to know the user tapped the send button or a function to know when a new message is sent?

**Comment by frankus** [comment]
The SDK fires the `ApptentiveMessageSentNotification` when the user sends a message in Message Center, which should let you do that.

**Comment by yangchen-acc** [comment]
Hi Frankus, thanks for the response, but when we sendAttachment it will trigger that notification again which might not be an ideal notification to listen to, I would be optimal if we can tell it's from a user-initiated event

**Comment by frankus** [comment]
You should find a `ApptentiveSentByUserKey` in the notification's `userInfo` dictionary with a `Bool` (or `NSNumber` in Objective-C) indicating if it was user-initiated. 

Hopefully that makes it work for you. This should definitely be documented a bit better!

**Comment by yangchen-acc** [comment]
Cool! That will help, thanks
