### ISSUE TITLE
On version 5.2.5 & iOS 13 whole survey screen is pink, and no content is shown.

### ISSUE THREAD

**Issue by sonjh1217** [apptentive/apptentive-ios#239]
On version 5.2.5 & iOS 13 whole survey screen is pink, and no content is shown.
![윤주호_20190916_205350_3](https://user-images.githubusercontent.com/7251802/64957524-20641700-d8c8-11e9-987d-758dfac9e5f1.png)

It works fine on  version 5.2.5 &  iOS 12 
or on version 5.2.2 & iOS 13
![KakaoTalk_Image_2019-09-16-21-24-43](https://user-images.githubusercontent.com/7251802/64957653-67eaa300-d8c8-11e9-9f3d-5232f80df1d7.png)

**Comment by frankus** [comment]
Thank you for the report. I will take a look at this right away.

**Comment by frankus** [comment]
We've identified the cause of this issue. It occurs when Apptentive iOS SDK version 5.2.5 is built on Xcode 10 and run on a device running iOS 13. 

If you are unable to wait for a release that fixes this bug, please use version 5.2.4 in the meantime, or build your app using the latest Xcode 11 GM seed. 

Again, thank you so much for reporting this issue! We will release a fix as soon as possible.

**Comment by sonjh1217** [comment]
Thank you!
