### ISSUE TITLE
App Stuck after pressing YES in Love Dialog

### ISSUE THREAD

**Issue by maheshvenkitachelam** [apptentive/apptentive-ios#241]
The app gets stuck after i press YES in Love dialog and the rating screen never comes up.

I am using a 12.3.1 iphone 7 for testing and 5.2.4 apptentative.

**Comment by vbrapptentive** [comment]
Hello @maheshvenkitachelam  - thanks for reaching out! Would you be able to contact our support team: support@apptentive.com, and include details about the company and app you are working on? Our team will be able to assist further from there.

Thanks so much,

Veronica

**Comment by CaseyApptentive** [comment]
Hi @maheshvenkitachelam. I wanted to follow up. Can you reach out to support@apptentive.com? From there we'll be able to help you directly. 

Thanks!

Casey
