### ISSUE TITLE
iOS 13: Can't re-present message center after pull-to-dismiss

### ISSUE THREAD

**Issue by richkolasa** [apptentive/apptentive-ios#242]
After dismissing message center via new modal pull-to-dismiss, it cannot be presented again.

**Comment by frankus** [comment]
Thank you for the report. We will look into this right away and get back to you.

**Comment by vbrapptentive** [comment]
@richkolasa we have just released our 5.2.7 SDK which addresses and resolves the issue you reported - thanks for sharing that!

Please upgrade to the latest version and contact support@apptentive.com if you have any further issues.

**Comment by richkolasa** [comment]
@vbrapptentive @frankus Thank you!
