### ISSUE TITLE
Message Center won't reopen if dismissed via gesture (iOS 13)

### ISSUE THREAD

**Issue by dauby88** [apptentive/apptentive-ios#244]
iOS 13 allows modals to be dismissed with a swipe gesture and this is not being handled for the Message Center presentation. 

After dismissing Message Center with a swipe gesture (instead of the "Close" button), opening  Message Center again fails and the following message is logged: "Apptentive message center controller already shown."

**Comment by vbrapptentive** [comment]
Hi @dauby88 - we have just addressed and resolved this in our latest SDK, 5.2.7. Can you please upgrade and contact support@apptentive.com if you have any further issues?

**Comment by dauby88** [comment]
Well I probably should have updated to the latest version before logging the issue...oops. Thanks!

**Comment by vbrapptentive** [comment]
No worries! Please keep us in the loop if you have any additional issues and thanks for reaching out.
