### ISSUE TITLE
Can't get notifications for iOS 13

### ISSUE THREAD

**Issue by timonchev** [apptentive/apptentive-ios#245]
Hello, I didn't get notifications for iOS 13. Please check this. because Apple did changes with deviceToken. Now it seem that broken.

Thanks

**Comment by CaseyApptentive** [comment]
Thanks for reaching out @timonchev. Can you email me at support@apptentive.com with which app you're working on specifically? I'd like to take a closer look at your setup to troubleshoot. 

Thanks again!
