### ISSUE TITLE
Update to version 5.2.7 via cocoapods

### ISSUE THREAD

**Issue by YodaVN** [apptentive/apptentive-ios#246]
I can't update from 5.2.3 to the latest version 5.2.7 by cocoapods. Is there anyway I can update it by cocoapods?

**Comment by frankus** [comment]
Just to be clear, is `pod update apptentive-ios` not grabbing version 5.2.7? Do you have any version restrictions in your Podfile that might excluding version 5.2.7?

**Comment by YodaVN** [comment]
Hi @frankus, that's my bad, something is wrong with my pod file. I deleted it and re-create, now it can update to 5.2.7

Thanks.
