### ISSUE TITLE
Can not switch to another configuration after the first initialization (via mParticle)

### ISSUE THREAD

**Issue by nic0mic** [apptentive/apptentive-ios#249]
Hi,

We are using Apptentive iOS via the [mParticle kit](https://github.com/mparticle-integrations/mparticle-apple-integration-apptentive).

The SDK is initialized a first time with **development API keys** (ie project A on Apptentive)
We can receive the events and the rating dialog is working.

The problem is if we decide to switch to the **production API keys** (ie Project B on Apptentive), the SDK is "blocked" with the first API keys. Events are sent to development even if we initialize with the production keys.
Using mParticle we have different projects and configurations per territories for our app. mParticle returns us the correct API keys.

How can we re-initialize the SDK with correct API keys?

We tried to delete the apptentive data directory (iOS simulator files) (`LIbrary/Application Support/com.apptentive.feedback`) when the app is closed, and it is working. 
On the next launch, the app will initialize with the other (correct) API keys.
But we cannot use this (hack) solution on real devices.

Do you have any ideas?

**Comment by CaseyApptentive** [comment]
Hi @nic0mic !

Thanks for the thorough details. Happy to help. 

Our SDK uses a standard 8 hour caching period, which it sounds like you're running into. When testing on real devices, the best thing to do is to fully uninstall then reinstall the app. This takes a bit of leg work, but it is the best way to ensure a clean testing environment as it forces a fresh manifest (which we use for targeting rules) to be fetched, as well as resetting counts to zero (for example, the Love Dialog is designed to be shown to a single user once per version of the app). 

We do have some ways that could expedite testing, but I'd recommend starting with uninstalling + reinstalling in an actual app first -- that way we ensure that everything is working. 

Then, if you're testing specific features, let me know specifically what you're trying and I may be able to help with some shortcuts (we have options, but they depend on some other factors like how your app versioning works, or if you are testing a debug build). 

Let me know if that works. 

Also, can you email us at support@apptentive.com with details on which app you're working on? I'd love to loop in your Customer Success Manager so they can make sure everything is running smoothly for you as well.

**Comment by CaseyApptentive** [comment]
@nic0mic taking a look at this with my engineers now. We'll be in touch with next steps as soon as possible. 

Thanks!

**Comment by frankus** [comment]
Hi @nic0mic,

Right now our SDK doesn't support changing the app key/signature after the first call to "register". The app key and signature are only used to create the session for the app (referred to as a "conversation" in the code), and after that the particular app install is pinned to that key/signature. 

I'm not sure if it would be a good fit for your workflow, but usually we would recommend creating multiple "apps" on mParticle, and changing the mParticle credentials on a per-territory (and/or per-environment) basis, but not changing the Apptentive credentials once they've been set for that territory and/or environment. 

Like you said, the only way to have the app key/signature change take effect is to delete the Apptentive data container.

**Comment by CaseyApptentive** [comment]
@nic0mic could you email us at support@apptentive.com with the name of the app you're working on? Then I can loop in your Customer Success Manager and they can assist in setting up a test app dashboard.

**Comment by nic0mic** [comment]
Thank you for the quick answer!
@frankus I was afraid of this, we currently have different mParticle workspace like you said.
We will find a solution to be able to test/changing the configuration, it is more a process to follow/be careful about now we know it will be always initialized with the first configuration set.

thank you!
