### ISSUE TITLE
[ApptentiveLogFileWriteTask execute] /apptentive-ios/Apptentive/Apptentive/Misc/ApptentiveLogFileWriteTask.m:64

### ISSUE THREAD

**Issue by smani21** [apptentive/apptentive-ios#250]
We are using 'apptentive-ios', '~> 5.2.7' 
Still we are getting this crash.

<img width="385" alt="Screen Shot 2020-02-03 at 3 45 46 PM" src="https://user-images.githubusercontent.com/53021310/73700775-526dee00-469c-11ea-8765-3780af842350.png">

**Comment by CaseyApptentive** [comment]
Hi @smani21. Thanks for reaching out, and apologies that you're seeing a crash. 

Can you send the full crash report to casey@apptentive.com? Happy to take a closer look and help with next steps.

**Comment by CaseyApptentive** [comment]
@smani21 Looks like this issue has been resolved -- is that right?

Happy to help if you need anything.
