### ISSUE TITLE
Cannot compile using Xcode 11.3.1

### ISSUE THREAD

**Issue by karansota** [apptentive/apptentive-ios#253]
Unable to build on Xcode 11.3.1

![Screen Shot 2020-03-04 at 11 27 05 AM](https://user-images.githubusercontent.com/2958150/75915338-2a90b800-5e0b-11ea-8f43-5a41e8b1bce3.png)

**Comment by CaseyApptentive** [comment]
Hi @karansota !

Thanks for reaching out and letting us know. My colleague, Marta, mentioned that she's on an email thread with you already. Moving the conversation there to help coordinate all parties. 

We'll be in touch shortly.
