### ISSUE TITLE
Prevent iOS13 swipe to dismiss

### ISSUE THREAD

**Issue by juliomb** [apptentive/apptentive-ios#256]
We would like to prevent swipe-to-dismiss to happen on iOS13 because some users are dismissing surveys by mistake. It can be easily achieve doing
`viewController.isModalInPresentation = true`
but since we don't have a reference to the `ViewController`, we can't make the change.

Thanks in advance.

**Comment by CaseyApptentive** [comment]
Hi @juliomb ! I'll share your feedback with my product team. 

Always love the feedback on how to improve our product.
