### ISSUE TITLE
MobileCoreServices has been renamed. Use CoreServices instead.

### ISSUE THREAD

**Issue by colinrf** [apptentive/apptentive-ios#262]
After upgrading to Xcode 11.4 I have new project warnings from Apptentive. 

`MobileCoreServices has been renamed. Use CoreServices instead. `

**Comment by CaseyApptentive** [comment]
Thanks for reaching out @colinrf. Taking a look at this with my team. 

We'll be in touch as soon as possible.

**Comment by CaseyApptentive** [comment]
@colinrf thanks again for the report! 

We've tried to repro it using Xcode 11.4 but are not able to. Can you help use with a bit more information?

- What app are you working on? If you'd prefer, please email support@apptentive.com with details so we can help coordinate.
- Is this blocking you from release, or urgent in any other way?
- How are you integrating Apptentive with your app? Any additional details that will help us repro this would be helpful.

**Comment by chrismcs** [comment]
Apptentive has been giving us the same warning in our project (we have it installed via cocoapods).  Looks like the linked PR should fix it.  Just checking to see if you'll be merging it anytime soon - we prefer to keep our project warning-free if possible.  Thanks!

**Comment by CaseyApptentive** [comment]
Hi @chrismcs ! Thanks for letting us know. We do not have this on our near term roadmap but will let you know if that changes. 

Would you mind emailing us at support@apptentive.com and tell us which app you're working on? I'd like to keep your Account Manager in the loop so they can help track. Just mention that you reached out on GitHub. 

Last we tried, we were unable to repro this in our own tests. It sounds like you integrated via cocoapods. If there are any other details that could help us repro, let us know. 

Thanks again.

**Comment by akcelotechnology** [comment]
Hi @CaseyApptentive, I'm also seeing this warning with Xcode 11.5 and Apptentive 5.2.11. We're using it for a hight profile client and would like to remove this warning. I'm emailing support with app details. Thanks!
