### ISSUE TITLE
Delegate or Notification observer or completion handler for when an event is cancelled or when user submit the feedback.

### ISSUE THREAD

**Issue by vinaykrishnan** [apptentive/apptentive-ios#268]
Can any one help in here with getting the completion handler when user cancel the survey or submit the survey. 

Code snippet :  Apptentive.shared.engage(event: event, from: controller)

**Comment by frankus** [comment]
We do publish an `ApptentiveSurveySentNotification` that's fired when the user submits a survey response, but currently there is no way to detect the user cancelling the survey.

**Comment by vinaykrishnan** [comment]
Hi Frankus, thank you so much for the response, ApptentiveSurveySentNotification well this will help, unfortunately i also needed a call back to handle the event when user cancel the Survey.

**Comment by vinaykrishnan** [comment]
Any thoughts of having it? Well this could be a benefits to analyze users participation in a survey.

**Comment by CaseyApptentive** [comment]
Hi @vinaykrishnan. Thanks for the suggestion -- happy to share it with my Product team.

it sounds like your Apptentive Dashboard should help with this. On your Dashboard, we analyze Survey data. This includes responses as well as things like response rate. Response rate specifically would show you how many people saw a Survey versus how many completed submitting answers. 

![Screen Shot 2020-04-28 at 2 26 36 PM](https://user-images.githubusercontent.com/29615280/80539437-57b99c80-895c-11ea-90a5-8deef7764dbd.png)

Would that accomplish what you're looking for?

**Comment by vinaykrishnan** [comment]
@CaseyApptentive @frankus , thanks for the reply. 

It will definitely helps us.

The issue in IOS 13 is when a view is presented, it don't cover the full screen, so the view presenting it is never notified when it is dismissed i.e  viewdidappear, viewwillappear methods are not called. For more information you can browse this 
 (https://stackoverflow.com/questions/56568967/detecting-sheet-was-dismissed-on-ios-13)

And i looped through the code there is no way i can extend the classes to achieve the above functionality.

**Comment by mknippen** [comment]
I'm having a similar issue. I just opened a ticket and a PR that adds a notification that should solve this problem. It's only a few lines of code and would really help:

https://github.com/apptentive/apptentive-ios/pull/272

**Comment by frankus** [comment]
This is now part of the 5.2.12 release.
