### ISSUE TITLE
There's no way to see when a user cancels a survey

### ISSUE THREAD

**Issue by mknippen** [apptentive/apptentive-ios#271]
In the current version of the SDK, we have notifications where when a survey is shown to a user, and when the user successfully sends a survey. We do not, however have a way to tell when the survey has been cancelled. 

This has been requested by a client of mine. I've went through and added this specific notification in a fork. It's 3 lines of code, and follows MVVM.

Please consider reviewing/merging. Thanks!

**Comment by frankus** [comment]
This is now part of the 5.2.12 release.
