### ISSUE TITLE
Crash on iOS simulator due to thread sanitizer

### ISSUE THREAD

**Issue by weiyin** [apptentive/apptentive-ios#279]
Hi,

My app is crashing on the iOS simulator with this message:

Dyld Error Message:
  Library not loaded: @rpath/libclang_rt.tsan_iossim_dynamic.dylib
  Referenced from: /Users/USER/Library/Developer/CoreSimulator/Devices/74A87809-190C-472A-A816-22EFD6C66BA3/data/Containers/Bundle/Application/AEB7C748-3563-4CDD-9F46-6D796B1DA30A/News.app/Frameworks/Apptentive.framework/Apptentive
  Reason: image not found

This seems to be caused by the thread sanitizer being enabled in Apptentive's project, similar to this issue: https://github.com/apollographql/apollo-ios/issues/859

Can you remove thread sanitizer from your project's schemes?

**Comment by CaseyApptentive** [comment]
Hi @weiyin ! Thanks so much for reaching out, and I'm sorry for the issue. Are you seeing this when you upgrade to the latest iOS SDK, v 5.2.12?

Let me know and we'll take a look as soon as possible.

**Comment by frankus** [comment]
Looks like this got included in the 5.2.9 update: https://github.com/apptentive/apptentive-ios/commit/1be524208ac5820b101b662a325666fae181536c#diff-e7f5430df36a3eb5a8c236ca79911f41R57. 

Hoping to have a release out soon that will revert that change. Thanks for bringing it to our attention!

**Comment by weiyin** [comment]
Thanks, looking forward to the release!

**Comment by frankus** [comment]
This should be fixed as part of https://github.com/apptentive/apptentive-ios/releases/tag/v5.2.13.
