### ISSUE TITLE
iOS 14 clipboard permission notification 

### ISSUE THREAD

**Issue by heinst** [apptentive/apptentive-ios#282]
We had a few users on the iOS 14 beta for our banking application contact us about them feeling uncomfortable about a banking application reading the clipboard, rightfully so. iOS 14 now tells users when apps have permission to their clipboard. It appears apptentive does in the background trying to read if the debug token is on the clipboard. Is this something that will be looked into so our users feel more comfortable using our banking app?

**Comment by frankus** [comment]
We released version 5.2.12 a couple of weeks ago to address this, but we recommend updating to 5.2.14 as it contains a few additional fixes.
