### ISSUE TITLE
Advertising Identifier

### ISSUE THREAD

**Issue by DanMorganiOS** [apptentive/apptentive-ios#286]
Hi Apptentive Team,

I noticed in this file [here we are trying to access the advertising identifier](https://github.com/apptentive/apptentive-ios/blob/master/Apptentive/Apptentive/Engagement/Model/ApptentiveDevice.m#L82) off the device. With the changes to IDFA in iOS 14 do you anticipate changing/removing this code? Will my app with your SDK be compliant with the new  guidelines around the IDFA for submission with Apple?

**Comment by CaseyApptentive** [comment]
Hi @DanMorganiOS. Great question, and one that's especially important with iOS 14. 

We do not collect IDFA. It's a field on our backend that is available, but it is turned off by default.  

This has been the case for every app we work with and it has not been an issue with submissions.

Let me know if you have any additional questions

**Comment by frankus** [comment]
The unused IDFA collection code has been removed in the new 5.3.2 release.
