### ISSUE TITLE
Crash when receiving update in a SwiftUI app

### ISSUE THREAD

**Issue by axello** [apptentive/apptentive-ios#295]
We are --trying to-- implement Apptentive in a swift + SwiftUI based app. As a host viewcontroller for Apptentive we are using a UITabBarController. The app can succesfully send engage(event:) messages, but when a notification from apptentive arrives the app crashes in @main.

Is there a recommended way to use apptentive-ios with SwiftUI based applications?

Apptentive 5.3.3

**Comment by CaseyApptentive** [comment]
Hi @axello. Sorry that you're seeing issues. I'll look into this with my team and get back to you as soon as possible.

**Comment by CaseyApptentive** [comment]
Circling back @axello. Thanks again for the report. This is not a known issue and we'll need a bit more information to understand what's going on. 

Could you send verbose logs from app launch until the crash?

Also, if you could share the name of the app you're working on, we could take a look at our backend to know more. If you'd rather, you can send that to me at support@apptentive.com and I'll help from there. 

Thanks!

**Comment by axello** [comment]
Hi, I'm on holidays. I've asked a colleague of mine to pick this up.

**Comment by CaseyApptentive** [comment]
Thanks! Let us know if there's any way we can help get logs. If it's easier and we can repro the issue, you could also send us a dev build. 

Whatever is easiest.

**Comment by CaseyApptentive** [comment]
Hi there. We'll still need more information, but I was able to get a sanity check from our iOS team. 

Unfortunately, we don’t yet support SwiftUI with our SDKs. But we would love to know more about exactly what you're looking for so we can share it with our Product team.  What type of notification are you looking to use? For example, push notification, NSNotificationCenter notification, or something else?

Also, what error message are you getting when your app crashes?

**Comment by axello** [comment]
We tested with our latest build and now it works without problems. Don't know what the reason was for the crashes, but you can close this ticket. Thanks.

**Comment by axello** [comment]
We tested with our latest build and now it works without problems. Don't know what the reason was for the crashes, but you can close this ticket. Thanks.

**Comment by TianleZhang** [comment]
Sry, we notice the issue only happened on real device but not on simulator
And when I dump the device log, I see this error
