### ISSUE TITLE
Crashed: com.apptentive.backend 

### ISSUE THREAD

**Issue by b3think3r** [apptentive/apptentive-ios#299]
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x8000000000000010 -> 0x0000000000000010 (possible pointer authentication failure)
Exception Codes: 0x0000000000000001, 0x8000000000000010
VM Region Info: 0x10 is not in any region.  Bytes before following region: 4342792176
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   102d9c000-103704000 [ 9632K] r-x/r-x SM=COW  ...rte.app/Porte
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [8170]

Thread 10 name:
Thread 10 Crashed:
0   libswiftCore.dylib            	0x0000000185a6f2f8 swift::RefCounts<swift::RefCountBitsT<(swift::RefCountInlinedness)1> >::incrementSlow(swift::RefCountBitsT<(swift::RefCountInlinedness)1>, unsigned int) + 60 (atomic:1006)
1   libswiftCore.dylib            	0x0000000185a36940 swift_retain + 124 (RefCount.h:813)
2   libswiftCore.dylib            	0x0000000185a773dc swift_bridgeObjectRetain + 56 (SwiftObject.mm:587)
**3                           	0x0000000103c094ec outlined retain of Person + 48 (<compiler-generated>:0)**
4                           	0x0000000103c270dc Backend.processChanges(from:) + 1544 (<compiler-generated>:0)
5                           	0x0000000103c05494 closure #1 in Apptentive.updateConversationPerson() + 444 (Backend.swift:43)
6                           	0x0000000102db61c4 0x102d9c000 + 106948
7   libdispatch.dylib             	0x0000000180969924 _dispatch_call_block_and_release + 32 (init.c:1517)
8   libdispatch.dylib             	0x000000018096b670 _dispatch_client_callout + 20 (object.m:560)
9   libdispatch.dylib             	0x0000000180972df4 _dispatch_lane_serial_drain + 672 (inline_internal.h:2601)
10  libdispatch.dylib             	0x000000018097399c _dispatch_lane_invoke + 444 (queue.c:3937)
11  libdispatch.dylib             	0x000000018097e1b8 _dispatch_workloop_worker_thread + 656 (queue.c:6727)
12  libsystem_pthread.dylib       	0x00000001f20730f4 _pthread_wqthread + 288 (pthread.c:2599)
13  libsystem_pthread.dylib       	0x00000001f2072e94 start_wqthread + 8

**Comment by frankus** [comment]
This looks like an issue that has been reported in our new SDK, https://github.com/apptentive/apptentive-kit-ios/issues/7. 

We have a fix available on a branch (https://github.com/apptentive/apptentive-kit-ios/tree/concurrency-fix) that you're welcome to try and we'll release a fixed version in the next few days.

**Comment by CaseyApptentive** [comment]
@b3think3r closing out some old issues. Let us know if you're still having any issues, always happy to help.
