### ISSUE TITLE
Swift compiler error when building Mac Catalyst app with Apptentive Swift package

### ISSUE THREAD

**Issue by rich-shimano-sap** [apptentive/apptentive-ios#300]
Adding the Apptentive framework via Swift Package Manager to our iOS/Mac Catalyst app causes the following compiler error when building the Mac Catalyst app (the iOS app builds fine) with Xcode 13.2.1+:

...SourcePackages/checkouts/apptentive-kit-ios/Sources/ApptentiveKit/Model/Environment.swift:160:35: error: cannot find type 'CTTelephonyNetworkInfo' in scope

<img width="794" alt="Screen Shot 2022-05-28 at 8 32 05 PM" src="https://user-images.githubusercontent.com/46009058/170850801-14956865-fe5b-4863-902e-6f6cfe20dd86.png">

<img width="795" alt="Screen Shot 2022-05-28 at 8 32 18 PM" src="https://user-images.githubusercontent.com/46009058/170850809-48edbea7-ec1d-41d3-8af7-55f08b802056.png">

**Comment by CaseyApptentive** [comment]
Hi @rich-shimano-sap, happy to help. Which version of the SDK are you using?

We've recently released a new version of our SDK with some big improvements, including support for Swift Package Manager: [6.0.2](https://github.com/apptentive/apptentive-kit-ios/releases/tag/v6.0.2)

Would you be open to using that version if you aren't already?

**Comment by rich-shimano-sap** [comment]
Sorry I forgot to mention it--we are using 6.0.2 and experiencing the Mac Catalyst build error with that Swift package.

**Comment by CaseyApptentive** [comment]
Thanks, @rich-shimano-sap. We'll look into this asap and get back to you. 

Is this holding up a release?

**Comment by rich-shimano-sap** [comment]
It is not holding up a release exactly--we would just prefer to use the latest SDK via Swift Package Manager, if possible. Thanks for your help!

**Comment by CaseyApptentive** [comment]
Thanks for the details! I'll be in touch as soon as I know more from my team.

**Comment by CaseyApptentive** [comment]
Hi @rich-shimano-sap. My team has made a branch that is available for testing here:
[apptentive-kit-ios: catalyst](https://github.com/apptentive/apptentive-kit-ios/tree/catalyst)

Can you give it a try and let me know the results?

**Comment by rich-shimano-sap** [comment]
That fix appears to work--both our iOS and Mac Catalyst app appear to build and archive successfully!

**Comment by CaseyApptentive** [comment]
Thanks for confirming. This was also released in [6.0.3](https://github.com/apptentive/apptentive-kit-ios/releases/tag/v6.0.3). Let us know if you need anything else.
