### ISSUE TITLE
AssertionFailures in SDK 6.0.x

### ISSUE THREAD

**Issue by jaishankar** [apptentive/apptentive-ios#301]
Team - With the SDK 6.0.x, we notice that Apptentive SDK uses assertion failure through out in many places, 

- when the registration key is not of valid format, 
- when there is a registration failure
- when there is a new credential being used without deleting the app

This breaks our app as we are providing an option in debug mode to switch between environments and on switching we will register with the appropriate credentials for the environment and restart the app flow. With 6.0.x this is breaking because of the assertion failures and there is no way for us to overcome this.

SDK should ideally throw an error which the app integrating the SDK should decide on how to deal with the error instead of SDK crashing the app with assertionFailure. Could you please consider this?

**Comment by jaishankar** [comment]
I realised I had posted in 5.x repo - so added few more details and posted in 6.0.x repo here - https://github.com/apptentive/apptentive-kit-ios/issues/18

**Comment by CaseyApptentive** [comment]
Thanks, @jaishankar. I'll close this thread in favor of the other one, [https://github.com/apptentive/apptentive-kit-ios/issues/18](https://github.com/apptentive/apptentive-kit-ios/issues/18)
