### ISSUE TITLE
No way to clear the conversation

### ISSUE THREAD

**Issue by ricsantos** [apptentive/apptentive-ios#49]
Also posted: http://stackoverflow.com/questions/18732596/apptentive-ios-sdk-clear-conversation

When a user logs out of my app, I need a way to clear the conversation that is saved by Apptentive.

Have tried:

``` objective-c
[[ATConnect sharedConnection] setInitialUserName:@""];
[[ATConnect sharedConnection] removeCustomPersonDataWithKey:@"name"];
```

**Comment by android1989** [comment]
+1

**Comment by levend** [comment]
@frankus is this still an issue? Our team consider integrating Apptentive, but we need multiuser support, or at least able to clear the sessions.

**Comment by frankus** [comment]
This is on our roadmap, but currently and in the immediate future we don't have a solution in place for multiple accounts or clearing sessions.

**Comment by sandor-gazdag** [comment]
@frankus can you please give us an estimate about when can we expect this issue to be resolved?

**Comment by frankus** [comment]
We're working on an initial version of this currently, and I'll update this issue as we get closer to release.

**Comment by frankus** [comment]
The latest version of the SDK allows you to isolate multiple users from one another. Please let us know if this fixes the issue for you.

**Comment by frankus** [comment]
Please take a look at our new customer authentication API in version 4.0.
