### ISSUE TITLE
New Delegate and Dismissal API for Interactions UI

### ISSUE THREAD

**Issue by wooster** [apptentive/apptentive-ios#86]
From #84:

<blockquote>
Ideally ATConnect would provide a delegate interface so that an application can detect when the ATConnect UI is no longer being shown. The delegate could provide callbacks for various interactions with the user, including dismissal. This can be useful for applications that gather usage statistics. The MFMailComposeViewControllerDelegate in iOS's MessageUI library is a good example of callbacks that would be useful for tracking the state of ATConnect.
</blockquote>

The current API we provide is fairly limited here, eg:

`- (void)dismissMessageCenterAnimated:(BOOL)animated completion:(void (^)(void))completion;`

We may have UI that this method call doesn't dismiss, such as ratings flow UIAlertViews, surveys, or upgrade messages.

This issue is for tracking adding new API for dismissing other UI elements that may be on screen, API for determining if there is UI being displayed, and callbacks/delegates for better control of displaying that UI.

/cc @lhasiuk

**Comment by pasevin** [comment]
Hey, is this still an issue? I still can't find documented delegate for Message Center dismissal. Need that for removing unread messages count badge.

**Comment by pkamb** [comment]
Hi @pasevin, you should be able to simply listen for the `ATMessageCenterUnreadCountChangedNotification` notification to clear a message count badge.

```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(unreadMessageCountChanged:) name:ATMessageCenterUnreadCountChangedNotification object:nil];
```

This ticket is for more of a notification when Apptentive's UI has been removed. Let me know if the notification doesn't work for your needs.

**Comment by pasevin** [comment]
hi, I'm using `NSNotificationCenter.defaultCenter().addObserver(self, selector: "unreadMessageCountChanged:", name: ATMessageCenterUnreadCountChangedNotification, object: nil)`
And it works, but not instantly. It takes sometimes up to a few minutes to execute. Not sure if that's normal. There is one case when user closes Message Center, I need to nullify the counter instantly. Now I do it when user opens Message Center manually, but there are cases when Message Center is launched from push notification. Then counter stays the same. Thats why I need to nullify the counter when user closes Message Center.
